### ISSUE TITLE
Conflict with Android Emulator/Intel HAXM

### ISSUE THREAD

**Issue by feuvan** [nlf/dlite#101]
When dlite is on, Intel HAXM failed, Android Studio gives log below:

> HAXM is working and emulator runs in fast virt mode
> emulator: Failed to sync vcpu reg
> Internal error: initial hax sync failed
> emulator: ERROR: Unfortunately, VirtualBox 4.3.30+ does not allow multiple hypervisors to co-exist.  In order for VirtualBox and the Android Emulator to co-exist, VirtualBox must change back to shared use.  Please ask VirtualBox to consider this change here: https://www.virtualbox.org/ticket/14294

after sudo killall dlite, the emulator works correctly.
Maybe need some investigation on how to use the hypervisors in "shared" mode?

**Comment by nlf** [comment]
this is an issue with xhyve and not something i can resolve at the dlite level, you'll want to open an issue on [the xhyve repo](https://github.com/mist64/xhyve)
