### ISSUE TITLE
support passing a DNS server to vm

### ISSUE THREAD

**Issue by qrpike** [nlf/dlite#103]
The docker VM doesn't seem to respect the hosts DNS servers which are obtained via DHCP.

It for some reason adds Google's DNS before the hosts DNS ( 8.8.8.8 )

**Comment by nlf** [comment]
correct. i'm going to be fixing this so that the default is to use the host's DNS server and you'll have the ability to manually set a DNS server as well.

**Comment by nlf** [comment]
edited title to reflect what i'm actually going to do
