### ISSUE TITLE
duplicate line in /private/etc/sudoers

### ISSUE THREAD

**Issue by holys** [nlf/dlite#106]
I  found three same lines in my  `/private/etc/sudoers`

```
... ...

## Read drop-in files from /private/etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /private/etc/sudoers.d

holys ALL=(ALL) NOPASSWD: /sbin/nfsd,/Users/holys/code/bin/dlite

holys ALL=(ALL) NOPASSWD: /sbin/nfsd,/Users/holys/code/bin/dlite

holys ALL=(ALL) NOPASSWD: /sbin/nfsd,/Users/holys/code/bin/dlite
```

Then I read the code. Found [this](https://github.com/nlf/dlite/blob/222d5b3af02ab965d4817885115bf0c1158fc396/utils%2Fsudo.go#L20)， which contains `\n`

```
sudoer := fmt.Sprintf("%s ALL=(ALL) NOPASSWD: /sbin/nfsd,%s\n", user, path)
```

while the [line](https://github.com/nlf/dlite/blob/222d5b3af02ab965d4817885115bf0c1158fc396/utils%2Fsudo.go#L34), which doesn't contain `\n` 

```
lines := strings.Split(string(sudoers), "\n")
```

so, [exists](https://github.com/nlf/dlite/blob/222d5b3af02ab965d4817885115bf0c1158fc396/utils%2Fsudo.go#L43) will be `false` forever. That's to say, every time you run `sudo dlite install`, you will append a line to `/private/etc/sudoers`

**Comment by nlf** [comment]
ah good catch, i'll get that fixed. thanks for reporting!
