### ISSUE TITLE
Unwanted warnings in Terminal window

### ISSUE THREAD

**Issue by ghost** [nlf/dlite#108]
I installed dlite using the instructions in the project README. I also uninstalled docker-machine and deleted the ~/.docker directory, because I understand they are no longer needed (?).

Now when I open a Terminal window, I always see these 2 lines before the first prompt:
`docker-machine dev is not running`
`try running: docker-machine start dev`

Any idea why this is happening? I previously created a docker machine called “dev”, but wasn't this machine deleted when I removed the ~/.docker directory?

**Comment by nlf** [comment]
your bash profile is still trying to run docker-machine, edit the `~/.profile` file and see if you see something running docker-machine in there. you'll need to delete that line

**Comment by ghost** [comment]
Thanks @nlf. Sheesh, where the heck did that file come from?
