### ISSUE TITLE
Kernel panic when macbook is in sleep mode

### ISSUE THREAD

**Issue by dcdej** [nlf/dlite#111]
Hello,

I have been having a kernel panic for some weeks now, the kernel panic only appears when the macbook goes to sleep for a longer period of time (in my case durung night time).

After running a dlite stop before putting the computer in sleep mode (before going to bed :)) I noticed that the kernel panic did not appear in the morning.

Im running dlite version 1.1.3

Here is my output from the kernel panic:

Tue Feb 23 04:39:45 2016

**\* Panic Report ***
panic(cpu 0 caller 0xffffff801b5d255a): Kernel trap at 0xffffff801b5b48ed, type 6=invalid opcode, registers:
CR0: 0x0000000080010033, CR2: 0x00007fff50f06110, CR3: 0x000000001e730000, CR4: 0x00000000003627e0
RAX: 0xffffff81254433d0, RBX: 0x0000000000000004, RCX: 0x0000000000000001, RDX: 0x00000000000058ca
RSP: 0xffffff81254433d0, RBP: 0xffffff81254433e0, RSI: 0x0000000000000000, RDI: 0x00000001559a4000
R8:  0xffffff801b5b48d0, R9:  0x00000001559a4000, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000004, R13: 0x0000000000000000, R14: 0x0000000000000000, R15: 0x0000000000000000
RFL: 0x0000000000010082, RIP: 0xffffff801b5b48ed, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007fff50f06110, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 2

Backtrace (CPU 0), Frame : Return Address
0xffffff8125443060 : 0xffffff801b4df792 
0xffffff81254430e0 : 0xffffff801b5d255a 
0xffffff81254432c0 : 0xffffff801b5f0233 
0xffffff81254432e0 : 0xffffff801b5b48ed 
0xffffff81254433e0 : 0xffffff801b5dc769 
0xffffff81254434d0 : 0xffffff801b5b0d12 
0xffffff8125443570 : 0xffffff801b5b92ed 
0xffffff8125443630 : 0xffffff801b5bba57 
0xffffff8125443650 : 0xffffff801b58e0a6 
0xffffff8125443670 : 0xffffff801b58b7bd 
0xffffff8125443790 : 0xffffff801ba7ca6a 
0xffffff8125443b90 : 0xffffff801b5df7fd 
0xffffff8125443bd0 : 0xffffff801b5be37a 
0xffffff8125443c60 : 0xffffff801b5defe3 
0xffffff8125443cd0 : 0xffffff7f9dec852d 
0xffffff8125443d10 : 0xffffff7f9decbd79 
0xffffff8125443d30 : 0xffffff801bad38ff 
0xffffff8125443d90 : 0xffffff801bafe9e6 
0xffffff8125443e00 : 0xffffff801baa48f9 
0xffffff8125443e60 : 0xffffff801ba9c884 
0xffffff8125443ec0 : 0xffffff801baa9b42 
0xffffff8125443f00 : 0xffffff801baa9c92 
0xffffff8125443f40 : 0xffffff801bab4d61 
0xffffff8125443f80 : 0xffffff801bab4f5c 
0xffffff8125443fb0 : 0xffffff801b5ccf77 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleACPIPlatform(4.0)[3BE4E926-E063-3BBD-BE05-F6F97358C7A4]@0xffffff7f9debd000->0xffffff7f9df1cfff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[5D7574C3-8E90-3873-BAEB-D979FC215A7D]@0xffffff7f9c442000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F398CE94-0FBD-3E8E-A7AB-55F7F05A81ED]@0xffffff7f9bd2c000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
15D21

Kernel version:
Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64
Kernel UUID: DECC9F02-27D7-31F0-9599-A9EF2873902C
Kernel slide:     0x000000001b200000
Kernel text base: 0xffffff801b400000
__HIB  text base: 0xffffff801b300000
System model name: MacBook8,1 (Mac-BE0E8AC46FE800CC)

System uptime in nanoseconds: 46128604973047
last loaded kext at 19768252812535: com.apple.driver.AppleBluetoothMultitouch   90.3 (addr 0xffffff7f9dff7000, size 57344)
last unloaded kext at 34870502797313: com.apple.driver.IOBluetoothHIDDriver 4.4.3f4 (addr 0xffffff7f9dfd7000, size 73728)
loaded kexts:
com.apple.filesystems.smbfs 3.0.0
com.apple.filesystems.autofs    3.0
com.apple.driver.AudioAUUC  1.70
com.apple.driver.AGPM   110.20.22
com.apple.driver.ApplePlatformEnabler   2.6.0d0
com.apple.driver.X86PlatformShim    1.0.0
com.apple.driver.AppleGraphicsDevicePolicy  3.7.7
com.apple.driver.AppleUpstreamUserClient    3.6.1
com.apple.driver.AppleOSXWatchdog   1
com.apple.driver.AppleHDA   272.51.3
com.apple.iokit.IOBluetoothSerialManager    4.4.3f4
com.apple.driver.pmtelemetry    1
com.apple.iokit.IOUserEthernet  1.0.1
com.apple.driver.AppleIntelBDWGraphics  10.1.2
com.apple.driver.AppleLPC   3.1
com.apple.Dont_Steal_Mac_OS_X   7.0.0
com.apple.driver.AppleHV    1
com.apple.driver.AppleBacklight 170.8.8
com.apple.driver.AppleCameraInterface   5.41.0
com.apple.driver.AppleIntelBDWGraphicsFramebuffer   10.1.2
com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
com.apple.driver.AppleMCCSControl   1.2.13
com.apple.driver.AppleSMCLMU    208
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
com.apple.BootCache 38
com.apple.driver.AppleTopCaseHIDEventDriver 86
com.apple.driver.AirPort.Brcm4360   1020.17.1a1
com.apple.driver.AppleSmartBatteryManager   161.0.0
com.apple.driver.AppleRTC   2.0
com.apple.driver.AppleACPIButtons   4.0
com.apple.driver.AppleHPET  1.8
com.apple.driver.AppleSMBIOS    2.1
com.apple.driver.AppleACPIEC    4.0
com.apple.driver.AppleAPIC  1.7
com.apple.nke.applicationfirewall   163
com.apple.security.quarantine   3
com.apple.security.TMSafetyNet  8
com.apple.kext.triggers 1.0
com.apple.driver.DspFuncLib 272.51.3
com.apple.kext.OSvKernDSPLib    525
com.apple.iokit.IOBluetoothHostControllerUARTTransport  4.4.3f4
com.apple.driver.AppleGraphicsControl   3.12.6
com.apple.iokit.IOSurface   108.0.1
com.apple.iokit.IOBluetoothFamily   4.4.3f4
com.apple.driver.CoreCaptureResponder   1
com.apple.driver.AppleBacklightExpert   1.1.0
com.apple.iokit.IONDRVSupport   2.4.1
com.apple.driver.AppleIntelLpssUART 2.0.59
com.apple.iokit.IOSerialFamily  11
com.apple.driver.X86PlatformPlugin  1.0.0
com.apple.driver.IOPlatformPluginFamily 6.0.0d7
com.apple.AppleGraphicsDeviceControl    3.12.6
com.apple.iokit.IOAcceleratorFamily2    205.1
com.apple.iokit.IOSlowAdaptiveClockingFamily    1.0.0
com.apple.driver.AppleHDAController 272.51.3
com.apple.iokit.IOHDAFamily 272.51.3
com.apple.iokit.IOAudioFamily   204.3
com.apple.vecLib.kext   1.2.0
com.apple.driver.AppleSMBusController   1.0.14d1
com.apple.driver.AppleSMC   3.1.9
com.apple.iokit.IOGraphicsFamily    2.4.1
com.apple.iokit.IOSCSIArchitectureModelFamily   3.7.7
com.apple.driver.CoreStorage    517.20.1
com.apple.driver.AppleHIDKeyboard   181
com.apple.driver.AppleMultitouchDriver  304.10
com.apple.driver.AppleHIDTransport  5
com.apple.driver.AppleHSSPIHIDDriver    41.7
com.apple.iokit.IONVMeFamily    1.1.0
com.apple.iokit.IO80211Family   1110.26
com.apple.driver.mDNSOffloadUserClient  1.0.1b8
com.apple.iokit.IONetworkingFamily  3.2
com.apple.driver.corecapture    1.0.4
com.apple.driver.AppleHSSPISupport  41.7
com.apple.driver.AppleIntelLpssSpiController    2.0.59
com.apple.driver.AppleHPM   1.2.5
com.apple.driver.AppleIntelLpssGspi 2.0.59
com.apple.driver.AppleIntelLpssI2CController    2.0.59
com.apple.driver.AppleIntelLpssDmac 2.0.59
com.apple.driver.AppleIntelLpssI2C  2.0.59
com.apple.driver.usb.AppleUSBXHCIPCI    1.0.1
com.apple.driver.usb.AppleUSBXHCI   1.0.1
com.apple.iokit.IOUSBFamily 900.4.1
com.apple.iokit.IOUSBHostFamily 1.0.1
com.apple.driver.AppleUSBHostMergeProperties    1.0.1
com.apple.driver.AppleEFINVRAM  2.0
com.apple.driver.AppleEFIRuntime    2.0
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.iokit.IOSMBusFamily   1.1
com.apple.security.sandbox  300.0
com.apple.kext.AppleMatch   1.0.0d1
com.apple.driver.AppleKeyStore  2
com.apple.driver.AppleMobileFileIntegrity   1.0.5
com.apple.driver.AppleCredentialManager 1.0
com.apple.driver.DiskImages 417.2
com.apple.iokit.IOStorageFamily 2.1
com.apple.iokit.IOReportFamily  31
com.apple.driver.AppleFDEKeyStore   28.30
com.apple.driver.AppleACPIPlatform  4.0
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily    1.4
com.apple.kec.Libm  1
com.apple.kec.pthread   1
com.apple.kec.corecrypto    1.0
Model: MacBook8,1, BootROM MB81.0164.B10, 2 processors, Intel Core M, 1,3 GHz, 8 GB, SMC 2.25f87
Graphics: Intel HD Graphics 5300, Intel HD Graphics 5300, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E4350544D4C42522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E4350544D4C42522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x131), Broadcom BCM43xx 1.0 (7.21.94.136.1a1)
Bluetooth: Version 4.4.3f4 16616, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus:

**Comment by hrzbrg** [comment]
This problem is known and does not occur anymore with 10.11.4 build 15E39d
Reference: https://github.com/mist64/xhyve/issues/86

**Comment by nlf** [comment]
yeah, this is a known issue with xhyve - we can't do anything to resolve it in dlite, so i'm going to close this
