### ISSUE TITLE
Mounted volume permissions issue after upgrading dlite

### ISSUE THREAD

**Issue by aleemb** [nlf/dlite#113]
I upgraded `dlite` just yesterday (from the ~3 weeks older version) and since then have had permissions issue on my mounts. All mounted volumes are owned by `501:root` and my server does not have write permissions to these folders throwing all kinds of errors after the upgrade. If I `chown` the mounted folders than the ownerships get messed up on the host.

Is there something that I should be aware of in the current versions of dlite that caused this? Things used to work just fine before the upgrade. What's the right approach here?

**Comment by nlf** [comment]
this is tricky because NFS mounts have a weird permission model. i'm trying to figure out the best way to get your UID embedded into the virtual machine, which would mean we don't have to worry about permissions at all. i think that's going to be the best solution for this.

well, that or not using NFS. but right now NFS is all we have :)

**Comment by emaiax** [comment]
I'm also having this issue after upgrading. All files created on my Rails' app by `rake` started to have weird permissions.

``` sh
~/code $ ls -lh app/models
total 8
drwxr-xr-x  3 emaiax  staff   102B Jan  8 18:28 concerns
-rw-r--r--  1 root    staff    58B Feb 26 01:16 user.rb
~/code $ dlite version
1.1.3
~/code $ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.6
 Git commit:   c3959b1
 Built:        Tue Feb 23 21:11:36 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

**Comment by bpinto** [comment]
I have altered my `/etc/exports` file to use my `uid` and `guid` instead. In order to make it work, after doing the changes I ran `sudo nfsd update` and restarted `dlite`.

```
#/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=root:wheel
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=bpinto:staff
```
