### ISSUE TITLE
install and setup issues: docker commands hanging.

### ISSUE THREAD

**Issue by supersophie** [nlf/dlite#114]
Hi,

 Installed dlite and have a VM running. 
 Can SSH into the VM.
From OSX docker commands do not return and hang for 10s of mins, and then I interrupt.  

Terminal 1,
$ sudo dlite daemon
COM1 connected to /dev/ttys001
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x34 on vcpu 0

Terminal 2,
$ ssh docker@local.docker
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
$ uname -a
Linux dlite 4.3.3-dhyve #1 SMP Sat Feb 6 00:10:17 UTC 2016 x86_64 GNU/Linux

Terminal 3, 
$ docker run helloworld
^C$ docker ps

What did I miss?

Thanks, Soph

**Comment by nlf** [comment]
if you run `docker ps` while in an SSH session in the virtual machine, does it work?

does the `/var/run/docker.sock` file exist?

**Comment by supersophie** [comment]
Hi Nathan,

In the container:
$ ssh docker@local.docker
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
$  
$ docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
$ ls -l /var/run/docker.sock 
srw-rw----    1 root     docker           0 Feb 24 20:01 /var/run/docker.sock

on the server:
$ ls -l  /var/run/docker.sock
srwxrwxrwx  1 root  daemon  0 Feb 24 21:01 /var/run/docker.sock

それでは、また。Sophie

**Comment by nlf** [comment]
inside the virtual machine, run `sudo cat /var/log/docker.log` and show me the output. it looks like the docker daemon is failing to start for some reason

**Comment by supersophie** [comment]
$ sudo cat /var/log/docker.log 
time="2016-02-24T20:01:54.980000000Z" level=warning msg="/!\ DON'T BIND ON ANY IP ADDRESS WITHOUT setting -tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING /!\" 
time="2016-02-24T20:01:54.980000000Z" level=fatal msg="Error starting daemon: Couldn't create Tag store repositories: EOF" 
$

**Comment by nlf** [comment]
try `sudo rm /var/lib/docker/repositories-btrfs` and then `sudo /etc/init.d/S51docker start` and see if `docker ps` works after that

**Comment by supersophie** [comment]
No luck :(

$ sudo rm /var/lib/docker/repositories-btrfs
rm: can't remove '/var/lib/docker/repositories-btrfs': No such file or directory

**Comment by nlf** [comment]
what does the output of `mount` look like? maybe the volume didn't get attached..

**Comment by supersophie** [comment]
$ mount
rootfs on / type rootfs (rw,size=1019976k,nr_inodes=254994)
devtmpfs on /dev type devtmpfs (rw,relatime,size=1019988k,nr_inodes=254997,mode=755)
proc on /proc type proc (rw,relatime)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /dev/shm type tmpfs (rw,relatime,mode=777)
tmpfs on /tmp type tmpfs (rw,relatime)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
sysfs on /sys type sysfs (rw,relatime)
/dev/vda1 on /var/lib/docker type btrfs (rw,relatime,space_cache,subvolid=5,subvol=/)
/dev/vda2 on /mnt/user type ext4 (rw,relatime,stripe=4,data=ordered)
overlay on /etc type overlay (rw,relatime,lowerdir=/etc,upperdir=/mnt/user/etc,workdir=/mnt/user/work/etc)
overlay on /home/docker type overlay (rw,relatime,lowerdir=/home/docker,upperdir=/mnt/user/home,workdir=/mnt/user/work/home)
192.168.64.1:/Users on /Users type nfs (rw,noatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.64.1,mountvers=3,mountproto=tcp,local_lock=none,addr=192.168.64.1)
none on /sys/fs/cgroup type tmpfs (rw,relatime)
none on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
none on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
none on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
none on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
none on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
none on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
none on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
none on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
none on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
none on /sys/fs/cgroup type tmpfs (rw,relatime)
none on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
none on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
none on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
none on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
none on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
none on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
none on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
none on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
none on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)

**Comment by nlf** [comment]
ah, my mistake. i forgot docker changed the file path. try `sudo rm /var/lib/docker/image/btrfs/repositories.json` and then `sudo /etc/init.d/S51docker start` and try again

**Comment by supersophie** [comment]
Looking much better.  Although could not d/l helloworld. It this related?

$ sudo rm /var/lib/docker/image/btrfs/repositories.json
$ sudo /etc/init.d/S51docker start 
Starting docker: OK
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ 
$ docker run helloworld
Unable to find image 'helloworld:latest' locally
Pulling repository docker.io/library/helloworld
docker: Error: image library/helloworld not found.
See 'docker run --help'.
$ 
$ docker pull helloworld
Using default tag: latest
Pulling repository docker.io/library/helloworld
Error: image library/helloworld not found

それでは、また。Sophie

**Comment by nlf** [comment]
the repo is `hello-world` not `helloworld` :) try it with the dash and it should work

**Comment by supersophie** [comment]
Yes that was it :)

Thank you so much for your help getting this running.

Sophie

$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
03f4658f8b78: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:8be990ef2aeb16dbcb9271ddfe2610fa6658d13f6dfb8bc72074cc1ca36966a7
Status: Downloaded newer image for hello-world:latest

**Comment by nlf** [comment]
you're very welcome
