### ISSUE TITLE
dlite daemon exits in 15 seconds

### ISSUE THREAD

**Issue by skatsuta** [nlf/dlite#115]
Hi, I installed dlite v1.1.3 on OS X 10.11.3 but `dlite start` didn't work.
So I directly started dlite daemon and it exited in 15 seconds as follows:

``` bash
$ sudo dlite daemon
COM1 connected to /dev/ttys007
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x34 on vcpu 0
Failed to find an IP for the virtual machine in 15 seconds
```

`sudo dlite install` seems to be done successfully:

``` bash
$ ls ~/.dlite
bzImage        config.json    disk.img       rootfs.cpio.xz

$ cat ~/.dlite/config.json | jq .
{
  "uuid": "83259a28-dab8-11e5-a038-f45c89ab54f3",
  "cpu_count": 1,
  "memory": 2,
  "hostname": "local.docker",
  "share": "/Users"
}
```

However I suspect it's strange to not exist the `/var/db/dhcpd_leases` file:

``` bash
$ ls /var/db | grep dhcpd

$
```

Could you tell me how to fix it? Thank you.

**Comment by nlf** [comment]
is your firewall enabled? if so, try disabling it and rebooting, and try starting dlite again. right now there seems to be some conflicts with the firewall. i'm working on a resolution for that.

**Comment by skatsuta** [comment]
Firewall in Security & Privacy preference is turned off. Is there any firewall elsewhere?

**Comment by nlf** [comment]
there is not.. does the `/var/db/dhcpd_leases` file exist at all? what about `/Library/Preferences/SystemConfiguration/com.apple.vmnet.plist`? does that plist have an entry with a UUID matching the one in your dlite config?

**Comment by skatsuta** [comment]
Yes, `/var/db/dhcpd_leases` does not exist at all...

Here is my whole `/Library/Preferences/SystemConfiguration/com.apple.vmnet.plist`, which doesn't have 
the UUID `83259a28-dab8-11e5-a038-f45c89ab54f3` mentioned above.

(Some of the information are masked)

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>MAC_ARRAY</key>
    <array>
        <dict>
            <key>MAC_ADDRESS</key>
            <data>
            xxxxxxxx
            </data>
            <key>MAC_TIME_USED</key>
            <date>2016-02-24T05:33:57Z</date>
            <key>MAC_USED</key>
            <false/>
            <key>UUID_MAC</key>
            <string>EA8B1D77-8CDA-XXXX-XXXX-XXXXXXXXXXXX</string>
        </dict>
        <dict>
            <key>MAC_ADDRESS</key>
            <data>
            xxxxxxxx
            </data>
            <key>MAC_TIME_USED</key>
            <date>2016-02-24T07:50:46Z</date>
            <key>MAC_USED</key>
            <false/>
            <key>UUID_MAC</key>
            <string>289A2583-B8DA-XXXX-XXXX-XXXXXXXXXXXX</string>
        </dict>
    </array>
    <key>MAC_IOUE_ARRAY</key>
    <array>
        <dict>
            <key>MAC_IOUE</key>
            <data>
            xxxxxxxx
            </data>
            <key>MAC_IOUE_USED</key>
            <false/>
        </dict>
    </array>
    <key>Shared_Net_Address</key>
    <string>192.168.64.1</string>
    <key>Shared_Net_Mask</key>
    <string>255.255.255.0</string>
</dict>
</plist>
```

**Comment by skatsuta** [comment]
This is what I forgot to say, my MacBook is a company one.
So there may be a special security protection in it (for example, I cannot use Hypervisor.framework?).
If so, this problem may be tricky...

**Comment by nlf** [comment]
looking at that it appears that vmnet isn't working. i'm not sure why that would be, however.

try booting the vm with xhyve directly (instructions below) so we can rule out something i'm doing in dlite as the issue

``` shell
brew install xhyve
sudo xhyve -A -c 1 -m 1G -s 0:0,hostbridge -l com1,stdio -s 31,lpc -s 2:0,virtio-net -s 4,virtio-blk,$HOME/.dlite/disk.img -U 83259a28-dab8-11e5-a038-f45c89ab54f3 -f kexec,$HOME/.dlite/bzImage,$HOME/.dlite/rootfs.cpio.xz,console=ttyS0 hostname=dlite uuid=83259a28-dab8-11e5-a038-f45c89ab54f3 share=/Users
```

that should boot, hopefully, but if it doesn't it should at least give us some more useful information. if it does boot, login with the username `root` and password `dhyve` and see if networking works.

**Comment by skatsuta** [comment]
Thank you for your quick troubleshooting. I've at least logged in to xhyve as follows, but some errors are found (Is this no problem?):

```
$ sudo xhyve -A -c 1 -m 1G -s 0:0,hostbridge -l com1,stdio -s 31,lpc -s 2:0,virtio-net -s 4,virtio-blk,$HOME/.dlite/disk.img -U 83259a28-dab8-11e5-a038-f45c89ab54f3 -f kexec,$HOME/.dlite/bzImage,$HOME/.dlite/rootfs.cpio.xz,console=ttyS0 hostname=dlite uuid=83259a28-dab8-11e5-a038-f45c89ab54f3 share=/Users
...(omitted)...
Starting rpcbind: NET: Registered protocol family 10
OK
Setting hostname:DONE
Starting network...
ifup: ignoring unknown interface eth0
Mounting NFS share:ip: RTNETLINK answers: Network is unreachable
tsc: Refined TSC clocksource calibration: 2698.053 MHz
clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x26e40f17ad6, max_idle_ns: 440795271011 ns
ip: RTNETLINK answers: Network is unreachable
clocksource: Switched to clocksource tsc
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
ip: RTNETLINK answers: Network is unreachable
FAIL
Starting dropbear sshd: OK
Starting docker: OK
Configuring sysctl: OK
Starting crond: OK
Starting NFS statd: done
Starting NFS services: exportfs: can't open /run/nfs/xtab for reading
done
Starting NFS daemon: rpc.nfsd: Unable to access /proc/fs/nfsd errno 2 (No such file or directory).
Please try, as root, 'mount -t nfsd nfsd /proc/fs/nfsd' and then restart rpc.nfsd to correct the problem
done
Starting NFS mountd: done

DhyveOS
dhyve login: root
Password:
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
#
```

**Comment by nlf** [comment]
you're definitely having networking issues.. unfortunately i'm not sure where to take it from here. you'll probably have to open an issue on the [xhyve](https://github.com/mist64/xhyve) repo, give them the details of the `xhyve` command above as well as the output in your last comment. also show the output of `ifconfig` from inside the VM.

hopefully someone there has some ideas, as i can't really do much with the networking stack on my end

**Comment by skatsuta** [comment]
I see, I'll head for xhyve repo. Thank you for navigating me!
