### ISSUE TITLE
Possible to change VM IP?

### ISSUE THREAD

**Issue by aleemb** [nlf/dlite#116]
Is it possible to change the VM IP from what it currently defaults to for me `192.168.64.9` to something else (for my case, I want `192.168.10.1`)? Any instructions would be welcome.

**Comment by nlf** [comment]
OS X assigns the IP dynamically, it would take some research to figure out how to change the subnet as well as assign a static IP. I'll put it on my list of things to figure out.

**Comment by nlf** [comment]
i wasn't able to find a reliable way of doing this, unfortunately
