### ISSUE TITLE
Question: Multiple Virtual Machines for Swarm and Consul set up

### ISSUE THREAD

**Issue by supersophie** [nlf/dlite#117]
Hi, 

How can I configure and run multiple VM hosts with dlite?
I would like to play with Swarm and Consul on my Mac.

Thanks and kind regards, Sophie

**Comment by kitten** [comment]
I think this is a job for Vagrant ;) https://www.vagrantup.com/

Edit: Here's a tutorial on how to do it http://blog.scottlowe.org/2015/03/06/running-own-docker-swarm-cluster/

**Comment by dirn** [comment]
Or Docker Machine

**Comment by nlf** [comment]
[corectl](https://github.com/thenewnormal/corectl) is also a good option for this since it lets you run a CoreOS cluster, which is a friendly environment for swarm.

unfortunately, any kind of multiple VM situation is out of scope for dlite. for now, at least. maybe someday in the future.
