### ISSUE TITLE
Default to all cpus (instead of 1) when installing

### ISSUE THREAD

**Issue by jakajancar** [nlf/dlite#118]
I understand that it makes sense to be conservative with disk space (until recompacting sparse images are supported) and memory (which is claimed fully over time), but why not default `--cpus` to all logical cores?

This way, you can still limit later when doing `docker run`, while in the current case, you have to re-install (and lose stuff).

**Comment by nlf** [comment]
you don't actually have to reinstall to raise the number of cpu cores in use, you can just `dlite stop` then edit `~/.dlite/config.json` and then `dlite start`.

i've considered raising the default number of cpu cores though, and i think this is a good idea.
