### ISSUE TITLE
Add command to ssh

### ISSUE THREAD

**Issue by grundic** [nlf/dlite#120]
First of all, great project, @nlf!
Would it be possible to add `ssh` command line option so it would looks like

```
dlite ssh
```

very like `docker-machine` does.

**Comment by nlf** [comment]
sure, why not :)

**Comment by grundic** [comment]
Would not it be better to use ip address instead of `local.docker`? Because user can configure any alias to the Docker host and connecting to ip looks more bulletproof.

**Comment by nlf** [comment]
i'm creating an ssh config entry now that has the IP listed in it,  but you're right i totally spaced that this needs to look up the actual hostname rather than hardcoding local.docker.
