### ISSUE TITLE
Installed using Brew and could not managed to start dlite - exit status 3

### ISSUE THREAD

**Issue by danieloliveira079** [nlf/dlite#121]
Installed using Brew
`sudo dlite install`
`dlite start -> Error: Exit status 3`

running `sudo dlite daemon`

`````` bash
COM1 connected to /dev/ttys003
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x34 on vcpu 0```

Looking to the source could I could notice the CreateAgent func which tries to create a folder inside $HOME/Library/ but I didnt get this folder created when running start.

any ideia?
``````

**Comment by nlf** [comment]
so your launch agent never got created? that's interesting.. when you run `sudo dlite daemon` does everything else work?

**Comment by danieloliveira079** [comment]
How can I check that? 

Yes looks like my agent never got created...

Any idea?

**Comment by nlf** [comment]
i have a new release ready for testing that i think will resolve this, see #135 for details and comment there if you're still having issues
