### ISSUE TITLE
DLite install fails on clean OSX installation

### ISSUE THREAD

**Issue by roblundiehill** [nlf/dlite#127]
dlite install fails because the ~/Library/LaunchAgents folder doesn't exist.

This folder should be created as required by the dlite install command.

OSX 10.10.5

**Comment by nlf** [comment]
it does, see https://github.com/nlf/dlite/blob/master/lib_agent.go#L39-L43

this hasn't been released yet though. i'll have a new release out soon.

**Comment by seanknox** [comment]
Hey @nlf, would it be possible to get a patch 1.1.x release to include this fix?

**Comment by nlf** [comment]
sure, I'll back port it and get a release out later today

**Comment by seanknox** [comment]
Thank you! dlite has made my Docker development much more delightful. :)

**Comment by nlf** [comment]
released 1.1.5 just now with this fix

**Comment by seanknox** [comment]
You're the best. Thank you!

**Comment by seanknox** [comment]
Submitted a PR to homebrew to support installing 1.1.5. Thanks again!

**Comment by okenwa103** [comment]
👍
