### ISSUE TITLE
Seamless routing issue

### ISSUE THREAD

**Issue by danielsmink** [nlf/dlite#128]
When running the commands listed for seamless routing I run into an error:

`ifconfig: BRDGSHOSTFILTER: No such file or directory`

Any idea how to resolve this? I've tried Googling but couldn't find anything related.

**Comment by deizel** [comment]
This happens when `$DOCKER_INTERFACE_MEMBERSHIP` is empty - try restarting `dlite`.

If you have trouble pinging, remove the route and start over: `sudo route -n delete 172.17.0.0/16`

**Comment by ruimarinho** [comment]
Can you paste the output of `echo ${DOCKER_INTERFACE}`and `ifconfig ${DOCKER_INTERFACE}`?

**Comment by danielsmink** [comment]
`danielsmink at Daniels-MacBook-Pro in ~
$ echo ${DOCKER_INTERFACE}


danielsmink at Daniels-MacBook-Pro in ~
$ ifconfig ${DOCKER_INTERFACE}
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128
	inet 127.0.0.1 netmask 0xff000000
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8823<UP,BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	ether 20:c9:d0:45:c2:7d
	nd6 options=1<PERFORMNUD>
	media: autoselect (<unknown type>)
	status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 32:00:17:9d:fc:a0
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 32:00:17:9d:fc:a1
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 2304
	ether 02:c9:d0:45:c2:7d
	media: autoselect
	status: inactive
awdl0: flags=8902<BROADCAST,PROMISC,SIMPLEX,MULTICAST> mtu 1452
	ether 36:06:99:51:b8:99
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether ae:87:a3:a0:a0:00
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
	inet 192.168.56.1 netmask 0xffffff00 broadcast 192.168.56.255
vboxnet1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:01
	inet 192.168.99.1 netmask 0xffffff00 broadcast 192.168.99.255
vboxnet2: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:02
	inet 192.168.59.3 netmask 0xffffff00 broadcast 192.168.59.255
en6: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether b6:e1:7a:6b:37:f1
	media: autoselect
	status: active
bridge100: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=3<RXCSUM,TXCSUM>
	ether 22:c9:d0:54:51:64
	inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en6 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 15 priority 0 path cost 0
	member: en7 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 17 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether ac:87:a3:0a:38:23
	inet6 fe80::ae87:a3ff:fe0a:3823%en5 prefixlen 64 scopeid 0x4
	inet6 2001:67c:1e8:66:ae87:a3ff:fe0a:3823 prefixlen 64 autoconf
	inet6 2001:67c:1e8:66:d0e4:370e:84a3:bd2b prefixlen 64 autoconf temporary
	inet 10.0.4.252 netmask 0xfffffe00 broadcast 10.0.5.255
	nd6 options=1<PERFORMNUD>
	media: autoselect (1000baseT <full-duplex,flow-control>)
	status: active
en7: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 42:29:ff:66:6a:5f
	media: autoselect
	status: active`

${DOCKER_INTERFACE} appears to be empty

**Comment by danielsmink** [comment]
```
danielsmink at Daniels-MacBook-Pro in ~
$ DOCKER_INTERFACE=$(route get local.docker | grep interface: | cut -f 2 -d: | tr -d ' ')

danielsmink at Daniels-MacBook-Pro in ~
$ echo ${DOCKER_INTERFACE}
bridge100

danielsmink at Daniels-MacBook-Pro in ~
$ DOCKER_INTERFACE_MEMBERSHIP=$(ifconfig ${DOCKER_INTERFACE} | grep member: | cut -f 2 -d: | cut -c 2-4)

danielsmink at Daniels-MacBook-Pro in ~
$ echo ${DOCKER_INTERFACE_MEMBERSHIP}
en6 en7

danielsmink at Daniels-MacBook-Pro in ~
$ sudo ifconfig "${DOCKER_INTERFACE}" -hostfilter "${DOCKER_INTERFACE_MEMBERSHIP}"
Password:
ifconfig: BRDGSHOSTFILTER: No such file or directory
```

As you can see neither are empty.

```
danielsmink at Daniels-MacBook-Pro in ~
$ ifconfig ${DOCKER_INTERFACE}
bridge100: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=3<RXCSUM,TXCSUM>
    ether 22:c9:d0:54:51:64
    inet 192.168.64.1 netmask 0xffffff00 broadcast 192.168.64.255
    Configuration:
        id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
        maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
        root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
        ipfilter disabled flags 0x2
    member: en6 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 15 priority 0 path cost 0
    member: en7 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 17 priority 0 path cost 0
    Address cache:
        42:b2:e8:55:cf:32 Vlan1 en7 645 flags=0<>
        8a:47:c4:6b:cf:32 Vlan1 en6 646 flags=0<>
    nd6 options=1<PERFORMNUD>
    media: autoselect
    status: active
```

**Comment by deizel** [comment]
For me `DOCKER_INTERFACE_MEMBERSHIP=en4`, so you might try setting yours to a single value instead:

``` sh-session
$ DOCKER_INTERFACE_MEMBERSHIP=en6
$ # or 
$ DOCKER_INTERFACE_MEMBERSHIP=en7
$ # followed by
$ sudo ifconfig "${DOCKER_INTERFACE}" -hostfilter "${DOCKER_INTERFACE_MEMBERSHIP}"
```

**Comment by danielsmink** [comment]
Setting it to en7 fixed it.

```
danielsmink at Daniels-MacBook-Pro in ~
$ docker inspect -f '{{.NetworkSettings.IPAddress}}' $(docker ps -q | head -1)
172.17.0.2

danielsmink at Daniels-MacBook-Pro in ~
$ ping 172.17.0.2
PING 172.17.0.2 (172.17.0.2): 56 data bytes
64 bytes from 172.17.0.2: icmp_seq=0 ttl=63 time=0.319 ms
64 bytes from 172.17.0.2: icmp_seq=1 ttl=63 time=0.330 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=63 time=0.456 ms
^C
--- 172.17.0.2 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.319/0.368/0.456/0.062 ms
```

**Comment by deizel** [comment]
Great - perhaps the `$DOCKER_INTERFACE_MEMBERSHIP` needs calculated differently.

My networking skills aren't that hot, but would piping through `tail -n1` solve similar cases?

**Comment by ruimarinho** [comment]
Interesting. @nlf do you know why/how bridge100 can have two interfaces connected? Is it possible to know which one redirects to the dhyve VM?

**Comment by nlf** [comment]
I have no idea, no. Sorry.

**Comment by ruimarinho** [comment]
In that case, we could possibly run a loop for each interface. @danielsmink did you notice any issue when setting the hostfilter to `en6`?

**Comment by danielsmink** [comment]
@ruimarinho yep setting it to en6 didn't work was still causing timeouts.

**Comment by ruimarinho** [comment]
Can you try this "one-liner"?

``` sh
DOCKER_INTERFACE=$(route get local.docker | grep interface: | cut -f 2 -d: | tr -d ' '); for interface in $(ifconfig ${DOCKER_INTERFACE} | grep member: | cut -f 2 -d: | cut -c 2-4); do sudo ifconfig bridge100 -hostfilter $interface 2> /dev/null; ping -q -c2 -t2 $(docker inspect -f '{{.NetworkSettings.IPAddress}}' $(docker ps -q | head -1)) > /dev/null; if [ $? -eq 0 ]; then echo; echo "Interface $interface configured"; break; fi; done
```

It basically loops through all of the interfaces available, pings them and then outputs which one responded to ping.

**Comment by danielsmink** [comment]
@ruimarinho works beautifully!

**Comment by maaarghk** [comment]
For anyone finding this from Google, as I did, if you have a member such as `en10` above command will trim it to `en1` so it won't work. Change `cut -c 2-4` to `cut -c 2-5`; pretty sure the whitespace won't hurt lower values. If you have en100 then start praying to the gods of awk.
