### ISSUE TITLE
Permissions rewritten on local environment to _appstore

### ISSUE THREAD

**Issue by greggilbert** [nlf/dlite#129]
Hey. This one is a bit weird. I just installed dlite this morning. Every time I run `dlite start`, it changes the permissions in my mounted folders to `_appstore:1000`:

`-rwxr-xr-x    1 1000  _appstore     2764 Oct 15 11:54 index.php`

Not sure what's going on there. I tried [bpinto's solution](https://github.com/nlf/dlite/issues/113#issuecomment-190190422) but that didn't solve the issue. Any ideas? Should I just wait until #123 is done?

**Comment by nlf** [comment]
yeah.. for now, wait until i finish with #123. this definitely sounds like an issue with the nfs share though

**Comment by greggilbert** [comment]
Sounds good. Super pumped to see this working!

**Comment by nlf** [comment]
this should be resolved in 2.0.0, see #135 for details on testing
