### ISSUE TITLE
Issues with TLS inside dlite virtual machine.

### ISSUE THREAD

**Issue by onnimonni** [nlf/dlite#130]
I started to investigate this after my `gem install` failed in my `docker build` with dlite:

```
ERROR:  Could not find a valid gem 'rspec' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (https://api.rubygems.org/specs.4.8.gz)
```

Then I tried https in dlite:

```
$ ssh docker@local.docker
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
$ wget https://rubygems.org/
Connecting to rubygems.org (54.186.104.15:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

dlite has been working perfectly until today I started to see these errors. I can't even use:

```
ADD https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 /tmp/
```

in my dockerfiles.

**Comment by ruimarinho** [comment]
Your base image probably lacks CA certificates. Try installing
"ca-certificates", "libssl" or "openssl".

On Thursday, March 3, 2016, Onni Hakala notifications@github.com wrote:

> I started to investigate this after my gem install failed in my docker
> build with dlite:
> 
> ERROR:  Could not find a valid gem 'rspec' (>= 0), here is why:
>           Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A (https://api.rubygems.org/specs.4.8.gz)
> 
> Then I tried https in dlite:
> 
> $ ssh docker@local.docker
> DhyveOS version 2.2.0
> Docker version 1.10.0, build 590d5108
> $ wget https://rubygems.org/
> Connecting to rubygems.org (54.186.104.15:443)
> wget: can't execute 'ssl_helper': No such file or directory
> wget: error getting response: Connection reset by peer
> 
> dlite has been working perfectly until today I started to see these
> errors. I can't even use:
> 
> ADD https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 /tmp/
> 
> in my dockerfiles.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nlf/dlite/issues/130.

## 

## 

Rui Marinho

**Comment by onnimonni** [comment]
My baseimage might have issues as well but this seems to be related in dlite. The same dockerfile was building perfectly in `hub.docker.com`.

**Comment by onnimonni** [comment]
Even destroying the box and starting a new one didn't resolve this for me.

```
$ docker-compose build
db uses an image, skipping
Building web
Step 1 : FROM alpine:edge
Pulling repository docker.io/library/alpine
ERROR: Service 'web' failed to build: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/alpine/images. You may want to check your internet connection or if you are behind a proxy.
```

Network works inside box but tls doesn't:

```
$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=49 time=33.401 ms
$ wget https://index.docker.io/v1/repositories/library/alpine/images
Connecting to index.docker.io (52.0.10.162:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
```

**Comment by onnimonni** [comment]
Sorry for the noise, This seems to be issue related in our office network. Closing for now
