### ISSUE TITLE
Cannot get dlite working.

### ISSUE THREAD

**Issue by divan** [nlf/dlite#131]
Hi,

I cannot get dlite working, docker API returns 503 and I also cannot log in into SSH. Here are details:

MacOS X 10.10.5 (14F27)
dlite installation: both from git master and from brew
`sudo dlite install -d 8`

After starting `dlite start`, I see /etc/hosts and /etc/exports updated correctly, also I can see dlite in the `ps ax` output, but docker commands return 503:

```
$ docker ps
Error: request returned Service Unavailable for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json, check if the server supports the requested API version
```

Trying to log in to VM, I get permission denied error, no matter which key I specify.

```
ssh docker@local.docker
docker@local.docker's password:
Permission denied, please try again.
docker@local.docker's password:
Permission denied, please try again.
docker@local.docker's password:
Permission denied (publickey,password).
```

I double checked hosts/IP, ssh keys, but everything looks ok.
I also uninstalled and reinstalled dlite a few times, but no luck.

The weirdest thing is that dlite was working before. Then there was some period without need to use docker, and now I cannot event find the cause of the problem.

Any suggestions where I can look to debug this problem?

Thanks in advance!

**Comment by nlf** [comment]
getting a 503 sounds like docker didn't start in the virtual machine. the most likely cause of this is your disk for dlite got messed up somehow. try running `dlite stop` then `dlite rebuild` and finally `dlite start` again. give it 30 or so seconds, and then see if things are working for you.

**Comment by divan** [comment]
Thanks for quick reply! Nope, rebuild don't work either.

```
$ dlite rebuild
Rebuilding disk image: ERROR!
exit status 1
```

**Comment by nlf** [comment]
did you install from master? if so there's a lot of work in progress code that isn't quite working yet. installing from the code in the releases or via homebrew is the latest known good build.

i'm hoping to have the next release out in the next week or so.

**Comment by divan** [comment]
Yes, switching to the brew version of dlite helped, and `dlite rebuild` successfully rebuild image.

Now, everything works, thanks for help and a great project!

**Comment by STRML** [comment]
@nlf I'm being affected by this same error in the 2.0 release with v3.0.0 of dhyve-os.
