### ISSUE TITLE
enable --insecure-registry option

### ISSUE THREAD

**Issue by genei09** [nlf/dlite#132]
I'm evaluating a private registry and it would be great to do it without having to get a real ssl cert and put it out on the cloud.

in boot2docker I can set the insecure-registry option just fine, but I haven't found a way to do it in dlite

**Comment by nlf** [comment]
this is already added to the new version of dlite in the form of allowing you to pass arbitrary flags to the docker daemon. release should be in the next week or so. closing this, but keep an eye on the 3.0.0 milestone

**Comment by JeremyGreaux** [comment]
Do you have news for add "--insecure-registry" ?
