### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bpinto** [nlf/dlite#133]
Should we have a new release with the amazing new features or perhaps support `HEAD` install on homebrew?

**Comment by nlf** [comment]
we will as soon as it's finished :)

i have to make changes to dhyve-os in parallel. have a little more patience with me, it's almost ready.

do note however, that the new version will _not_ be backwards compatible with the old. you'll have to run `dlite stop && sudo dlite uninstall` before installing the new version or things will fail spectacularly. i'll make sure to have documentation for that when i do the actual release

**Comment by bpinto** [comment]
:+1: 

Thanks for all the hard work! :tada:
