### ISSUE TITLE
/var/run/docker.sock not exists on OS X

### ISSUE THREAD

**Issue by zelgerj** [nlf/dlite#138]
Hi,

i just installed 2.0.0 with os 3.0.0 but `docker ps` won't work.
Doing a `docker ps` within dlite ssh session works.

A quick check if `/var/run/docker.sock`exists on my OS X shows that it is missing.
Any ideas?

Thanks

**Comment by zelgerj** [comment]
Ok it is strange.

`sudo nfsd status`sayed that nfsd is not active. So i activated it and did

```
dlite stop
dlite rebuild
dlite start
```

Now the docker.sock file exists but it says:

```
Error: request returned Service Unavailable for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.22/containers/json, check if the server supports the requested API version
```

If i login via ssh it says:

```
DhyveOS version 3.0.0
-sh: /etc/profile.d/dhyve.sh: docker: Permission denied
```

So i started the script manually without problems:

```
sh /etc/profile.d/dhyve.sh 
DhyveOS version 3.0.0
Docker version 1.10.2, build c3959b1
```

After that a `docker ps` in the dlite vm and on my OS X worked without problems.

For your informations:
It was on an absolutely fresh installation of OSX Version 10.11.4 Beta (15E56a) install.

**Comment by nlf** [comment]
nfsd isn't used at all in the latest version, so running it shouldn't have had any impact.

my best guess is that the docker daemon was still downloading when you were trying to run the commands initially, and when you ran the script manually it just so happens that the download had finished.

**Comment by nlf** [comment]
i'm going to try to see if i can come up with a way to get the docker cli to display real error messages so that i can better inform the user if a download is still in progress

**Comment by zelgerj** [comment]
Thanks for the infos! More error logging / mesages would be very handy in case of errors!
I like your project very much (great job! :+1: ) and will try to get deeper into code. Maybe i can help fixing some bugs.

Why are you downloading the docker binaries on demand? Wouldn't it be better to integrate the current docker version into your os images and provide an docker-update functionality which shows a progress bar etc?

**Comment by nlf** [comment]
we initially had the docker binary in the base image, but people wanted the ability to change versions more easily so we went this route. feedback has pretty much all been towards going back to how things were however, so i may do a hybrid sort of thing like you're suggesting

**Comment by nlf** [comment]
closing, see follow up here https://github.com/nlf/dhyve-os/issues/23
