### ISSUE TITLE
Horribly slow file descriptors over docker socket

### ISSUE THREAD

**Issue by akatrevorjay** [nlf/dlite#139]
docker logs -f blah is horrendously slow, is it not line buffered or something?
It's fast from the dlite VM over SSH, so there's some fuckery on that.

Another example is docker pull. The output comes in patches.

Ty for dlite by the way, been using it for a while now for some tasks!

**Comment by bpinto** [comment]
@akatrevorjay is it possible for you to create an example application with the same issues?

**Comment by akatrevorjay** [comment]
This problem isn't solved, it's just slightly better now.

Also the logs command doesn't work either, it just hangs.

Hmm

**Comment by akatrevorjay** [comment]
You can especially tell when watching a docker pull of an image, the refresh rate is not near what say docker-machine (xhyve or vbox drivers) provides.

**Comment by kitten** [comment]
I'm seeing this as well. For `logs`, `pull` and the likes I'm currently using ssh to circumvent this.

``` sh
  function dl () {
    nmap local.docker -PN -p ssh | grep -q 'open'
    if [ "$?" != "0" ]; then
      echo "Error: The SSH port is not opened at local.docker"
      return 1
    fi

    ssh -q -o "BatchMode yes" local.docker docker $@
    return 0
  }
```

`dl logs -f example`

**Comment by akatrevorjay** [comment]
I've found that it only seems to matter when streaming, ie using the `-f` option.

**Comment by nlf** [comment]
What seems to matter? Are you saying you get better performance streaming vs not streaming?

**Comment by akatrevorjay** [comment]
I'm saying streaming doesn't even work at all.

**Comment by akatrevorjay** [comment]
Non-streaming, ie `docker logs`, seems to work fine.

**Comment by akatrevorjay** [comment]
It's the proxy that's causing this.

It works fine going directly to port 2375. Also the CPU usage skyrockets by the dlite process during a simple download, no extraction. At the same time over SSH watching the system (ie `top` over SSH to the xhyve VM), theres's no cpu usage to be seen.

**Comment by akatrevorjay** [comment]
It's nearly unusable while streaming unfortunately, spite at the time has
high CPU usage that isn't seen from inside of the vm. Maybe the loop is too
tight in lib_proxy.go?

If I avoid the unix to tcp proxy and connect directly to port 2375, all is
well. An easy test is just watching the output of docker pull, you'll see
the refresh rate start out not so great,  and it at least appears to get
worse, multiple seconds in between updates.

**Comment by nlf** [comment]
i can replicate, working on a fix now

**Comment by nlf** [comment]
interestingly enough, it was actually the reverse of what we thought. streaming logs is a plain http request, not an upgrade request so it wasn't going over the raw socket. i've switched things to always hijack the request and use the raw socket instead, which from my testing has drastically improved things.

if you can, test out 2.0.0-beta4 and let me know how it looks for you

**Comment by akatrevorjay** [comment]
Yep, all better!
So, Docker uses long polling for streamed log output? Strange. Very strange.
