### ISSUE TITLE
Use of hardcoded 172.17.0.0/16 range

### ISSUE THREAD

**Issue by romanrev** [nlf/dlite#148]
I don't see a reason why there is a need to hardcode the 172.17.0.0/16 range and also consider that a bad practice. I think the IP range for the VMs/containers should be configurable.
Found at least one place in the code where this range occur:

https://github.com/nlf/dlite/blob/94751cc5c6807fdce70de33864d38799d9d74615/lib_route.go#L11

**Comment by nlf** [comment]
you're right, we'll make it configurable before the 2.0.0 final release
