### ISSUE TITLE
Default id_rsa.pub not $HOME/.ssh/id_rsa.pub

### ISSUE THREAD

**Issue by maltefiala** [nlf/dlite#15]
`sudo dlite install` is definitely not using $HOME/.ssh/id_rsa.pub.

Temporary fix is using `sudo dlite install -s "$HOME/.ssh/id_rsa.pub"`

**Comment by nlf** [comment]
this is a weird one since it's working correctly for me, but i think i have a workaround that will hopefully be more consistent

**Comment by nlf** [comment]
try out the 1.0.3 release i just pushed and let me know if that works for you

**Comment by maltefiala** [comment]
**Working, thanks a lot!**

Steps:

``` bash
rm -r ~/.dlite
sudo dlite install
sudo dlite daemon
COM1 connected to /dev/ttys002
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x34 on vcpu 0
sed -i '' -e '$ d' ~/.ssh/known_hosts
ssh docker@local.docker
DhyveOS version 2.0.0
Docker version 1.9.1, build a34a1d5
$
```

**Comment by nlf** [comment]
thanks for letting me know!
