### ISSUE TITLE
How could I disable dlite automated startup?

### ISSUE THREAD

**Issue by supersophie** [nlf/dlite#152]
Hi, 

 This maybe unrelated, but since I started using dlite I've had kernel panics when resuming from deep sleep. 

How could I disable dlite from automated system startup?  ( I've used "dlite stop" for the timebeing ).
I hope to remove dlite from the possible cause list. :)

Thanks,
So.

**Comment by nlf** [comment]
dlite is absolutely the cause, there's a bug in the frameworks that dlite uses that cause that crash. if you want to prevent dlite from starting automatically you can

```
launchctl unload ~/Library/LaunchAgents/local.dlite.plist
rm ~/Library/LaunchAgents/local.dlite.plist
```

**Comment by supersophie** [comment]
Hi and thanks Nathan.

Wondering if I deleted this earlier and forgot to reboot.

$ launchctl unload ~/Library/LaunchAgents/local.dlite.plist
/Users/sophie/Library/LaunchAgents/local.dlite.plist: Could not find specified service
$ ls -l  ~/Library/LaunchAgents/_dlite_
-rw-r--r--  1 sophie  staff  450 Feb 24 22:05 /Users/sophie/Library/LaunchAgents/local.dlite.plist

 For now I’ve changed,
                <key>RunAtLoad</key>
                <true/>

To be, 
                <key>RunAtLoad</key>
                <false/>

それでは、また。Sophie

**Comment by nlf** [comment]
great, glad you got it figured out :)
