### ISSUE TITLE
dlite fails to start if conflicting entries exist in /etc/exports

### ISSUE THREAD

**Issue by lazyguru** [nlf/dlite#153]
First, this project is great.  Thank you so much.

If an entry exists in /etc/exports for a path in the user's home directory (eg /Users/<username>/projects/myproject ) then dlite fails to start when using either `sudo dlite start` or using launchctrl.  System log reports:

`com.apple.xpc.launchd[1] (local.dlite[17835]): Service exited with abnormal code: 1
`

I only discovered the issue by running `sudo dlite daemon` which reported:

`Export verification failed:
exports:5: /Users conflicts with existing export /Users/<username>/projects/myproject
`

For me this wasn't a problem since the entry is related to using vagrant and I don't need the entry on a permanent basis

**Comment by nlf** [comment]
this is documented in the readme for that release. i should probably change the default branch back to what's in homebrew to eliminate confusion
