### ISSUE TITLE
Error: Cannot connect to docker daemon

### ISSUE THREAD

**Issue by lessless** [nlf/dlite#154]
Hello,

this looks like to be a support thread and maybe should be asked on stackoverflow or alike, but I didn't find any relevant "channel".

I'm running `OSX 10.11.3 (15D21)` and installed dlite (v. `1.1.4`) via homebrew with:

```
$brew install docker dlite
$sudo dlite install
$dlite start
```

but when I'm trying to boot postgis image there is an error:

```
$docker run mdillon/postgis:9.5
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

**Comment by nlf** [comment]
is dlite actually running? try `ps aux | grep dlite` and see if it's in there. if it's not, run `sudo dlite daemon` and let's see what that looks like

**Comment by lessless** [comment]
Thank you @nlf, it worked like a charm and was able to boot up the container.  Though I'm still experiencing problems and will greatly appreciate if you will have time to take a look  on http://stackoverflow.com/questions/36288646/cant-connect-to-postgresql-server-with-docker-and-dlite

**Comment by nlf** [comment]
i'm not on stackoverflow, but i can tell you at a glance the reason it's not working is you need to either follow the directions in the readme for seamless routing and refer to the container's IP directly, or you need to expose the port when you run the container (i.e. `docker run --rm -p 5432:5432 postgres`) which will then make the service available at the `local.docker` hostname

**Comment by lessless** [comment]
@nlf indeed  `docker run --rm -p 5432:5432 postgres`  saved the day! 
Regarding seamless routing  - do you mean  README in `master` branch? Brew provides only `1.1.4` version and there is no `route` command there :(

**Comment by nlf** [comment]
ah, i'm sorry, you're right. i forgot that we didn't have that documented in the legacy branch.

it's kind of a pain to setup, IMO for most use cases just exposing the port is the simplest solution anyway.

**Comment by lessless** [comment]
No problems! You saved me days of lurking through documentation :)
Btw, is port exposing a DLite-specific nuance? I never met that in documentation before.
If so, it will be great to have some auto-mapping flag, based on `EXPOSE` directive.
p.s. "issue" might considered  resolved.

**Comment by nlf** [comment]
it's not dlite specific, it's a docker thing. services that listen inside a container are only listening on an internal container network. if you want to access them outside of that network, you have to tell docker to expose them.

i'll go ahead and close this but let me know if you have any other questions
