### ISSUE TITLE
Conflicting entry in osx /etc/exports blocks NFS mount

### ISSUE THREAD

**Issue by csears** [nlf/dlite#157]
Greetings,

I was having trouble getting the NFS shared directory to work. It turned out that docker-machine-xhyve had added an entry to my /etc/exports for /Users that was conflicting with the dlite share for /Users. I removed the docker-machine-xhyve entry, restarted nfsd and everything is working.

Would it make sense to add a check/warning during install or startup to see if /Users is already being shared?

Thanks for your work on dlite!

**Comment by nlf** [comment]
this is only relevant for version 1.1.4 which is no longer being worked on. 2.0.0 has a completely different implementation for file sharing and isn't impacted by this at all.

since this is already documented in the readme for the legacy branch where it applies, i'm going to close this.

**Comment by csears** [comment]
My VM wasn't having trouble starting, so I must have skimmed right over the section at https://github.com/nlf/dlite/blob/legacy/README.md#troubleshooting

Thanks for the quick response.
