### ISSUE TITLE
django-runserver in a container constantly restarts

### ISSUE THREAD

**Issue by synic** [nlf/dlite#161]
I don't know if you are the guy to ask about this, it's just that with the regular docker-toolbox and virtualbox, this did not happen.

I have a container, in which I run `python manage.py runserver`.  This is the django development server.  One of it's duties is to detect filesystem changes, and reload itself if any python files have changed.

In this container, using the `dlite` vm, `runserver` is constantly detecting filesystem changes, and therefore, constantly reloading itself.  Unfortunately, I'm not actually making any changes, so I don't know why that's happening.  `runserver` also has the `--noreload` option, which will disable this feature.  When it's disabled, everything works fine (except django doesn't reload itself when a python file changes).

The only thing I can think of is weird NFS options.

Do you happen to know what it might be?

**Comment by nlf** [comment]
That's really weird seeing as NFS doesn't support filesystem notifications at all.. I can almost guarantee that the issue here is the shared FS. I'm working on some fixes for that for version 2.0

**Comment by synic** [comment]
Another weird thing I saw was a missing file.  It was a python file, visible on my local filesystem, but not visible inside the container.  Everything else was where it should be.  I could make changes and see them in the container.  This one file just plain wouldn't show up in an `ls`, but I could `cat` it (I know that sounds weird, but it happened).

**Comment by nlf** [comment]
is this with version 1.1.4 or 2.0.0 of dlite?

**Comment by synic** [comment]
2.0.0.  Should I use 1.1.4?

**Comment by nlf** [comment]
nah, just gathering info for diagnostics :)

i'm working on replacing the whole shared filesystem layer for 2.0.0 before i release it. can you by chance replicate this issue in a small isolated repo or an open source project? that would help me so i can test your case

**Comment by synic** [comment]
I can't even reproduce it now, with the same file.  I did increase the VM memory, and now it seems to be working better.  I'll fiddle around with it some more and let you know if I see it again

**Comment by synic** [comment]
Just a note.  I tried 1.1.4, and the constant restarting issue does not exist there.

**Comment by nlf** [comment]
we're back to nfs for the latest beta so this should be resolved https://github.com/nlf/dlite/releases/tag/2.0.0-beta7
