### ISSUE TITLE
BoringSSL build fails during packaging object files

### ISSUE THREAD

**Issue by kzemek** [nlf/dlite#162]
``` bash
$ git clone https://boringssl.googlesource.com/boringssl
$ docker run -ti --rm -v `pwd`/boringssl:/tmp/boringssl -w /tmp/boringssl/ golang bash
>$ apt-get update && apt-get install -y ninja-build cmake
>$ mkdir build && cd build
>$ cmake .. -GNinja
>$ ninja
/usr/bin/ar: crypto/x509/CMakeFiles/x509.dir/x_pkey.c.o: Operation not permitted
```

[Full container's logs on Pastebin](http://pastebin.com/URWYrv3M)

I don't think the problem is in any way specific to BoringSSL, it's just the first thing that fails in my own project's build. :)

This looks to be a problem on the filesystem's (`9p`) end, and unfortunately blocks me from migrating from `docker-machine` to `dlite`.

**Comment by nlf** [comment]
yeah, 9p was the wrong path to go down. you might try dlite 1.1.4 instead as it uses NFS. i'm hoping to have a new release out soon with an entirely different filesystem sharing layer

**Comment by nlf** [comment]
went back to nfs in master (not yet released) so closing
