### ISSUE TITLE
Ansible docker connection type fails to run any task

### ISSUE THREAD

**Issue by genei09** [nlf/dlite#164]
After some research with Ansible there seems to be a problem with the kernel in the dlite vm.

I can build and start containers with ansible, but I can't use the docker connection type to perform the equivalent of "docker exec"

**Comment by nlf** [comment]
if you can tell me what kernel features are required, i'm happy to fix it.

**Comment by genei09** [comment]
https://github.com/ansible/ansible/issues/13876

it looks like some sort of interaction with ssh

**Comment by genei09** [comment]
this is the thread on similar kernel issues
https://github.com/ansible/ansible/issues/13876

**Comment by genei09** [comment]
I can give you a sample playbook if that would help.

**Comment by genei09** [comment]
http://pastebin.com/z926PW0X
 use:
ansible-playbook bin/playbooks/main.yml -vvvv

**Comment by genei09** [comment]
the error message is:
`fatal: [test_dlite]: FAILED! => {"failed": true, "msg": "failed to resolve remote temporary directory from ansible-tmp-1460315994.27-40762714392695:`( umask 22 && mkdir -p \"`echo $HOME/.ansible/tmp/ansible-tmp-1460315994.27-40762714392695`\" && echo \"`echo $HOME/.ansible/tmp/ansible-tmp-1460315994.27-40762714392695`\" )`returned empty string"}`

(edited because posting the right error message is helpful)

**Comment by genei09** [comment]
EXEC ['/usr/local/bin/docker', 'exec', '-i', u'test_dlite', '/bin/sh', '-c', '/bin/sh -c \'( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1460407965.83-161144435727650`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1460407965.83-161144435727650`" )\'']

this is the call ansible is trying to make.  docker exec -i test_dlite /bin/sh -c mkdir -p && echo and for some reason it isn't getting the echo back.

but when I run this from the cli myself I do get the echo back.  So I'm not sure what it is listening for.  I did verify the playbook works with docker-toolbox on OSx and on linux natively.  So it's certainly something with dlite

**Comment by nlf** [comment]
this has all been reworked, feel free to open a new issue if you're still using dlite and have problems with the newest beta https://github.com/nlf/dlite/releases/tag/2.0.0-beta7
