### ISSUE TITLE
Forward filesystem events to vm's inotify

### ISSUE THREAD

**Issue by TomFrost** [nlf/dlite#165]
Related to #31

The [dinghy](https://github.com/codekitchen/dinghy) project recently solved this by using [fsevents_to_vm](https://github.com/codekitchen/fsevents_to_vm). Essentially it attaches an fswatch event listener on the mac side, and when a file is changed, it executes an [ssh command](https://github.com/codekitchen/fsevents_to_vm/blob/master/lib/fsevents_to_vm/ssh_emit.rb#L14) to `touch` the same file inside of the VM, thereby triggering an inotify event.

It would be lovely if this same sort of feature were baked into dlite. I truly love this project, but the lack of inotify means I still can't set my frontend team (heavily reliant on gulp and webpack watchers for their dev flow) up with a docker-based dev environment.

One of the things the above project does to avoid any complex configuration around this feature is to omit watchers from certain high-write folders that have a low probability of actually needing inotify events in the VM-- such as `/Users/*/Library` and `*/.git/*`. That may allow this to be implemented here without any noticeable performance cost.

**Comment by TomFrost** [comment]
Note: I've confirmed fsevents_to_vm does actually work with dlite, with some modifications:
- The `touch` command in `ssh_emit.rb` must be run as `sudo`
- The executable requires additional arguments. I ran it with: `fsevents_to_vm start --debug --ssh-identity-file=~/.ssh/id_rsa --ssh-ip $(dlite ip)`

I still heavily suggest this functionality be implemented within dlite itself, rather than using this directly -- I just wanted to share a stopgap, and confirm that this approach will in fact work.

**Comment by nlf** [comment]
and does it work with the old nfs setup, or with the newer p9? the major issue with an approach like this is a network filesystem that transmits "touch" events back to the server will get stuck in a loop. server notifies client, client touches file, server sees the touch as another event and sends it back to the client again.

**Comment by TomFrost** [comment]
Definitely understand the looping problem -- it looks like fsevents_to_vm solves that by passing arguments to `touch` to make sure the `mtime` matches the fswatch event that kicked off the touch, and caches that event. Then, when another event comes in, it checks to see if the mtime matches the cached event's mtime and ignores it if so. See the implementation here: https://github.com/codekitchen/fsevents_to_vm/blob/master/lib/fsevents_to_vm/recursion_filter.rb

I just upgraded to 2.0.0-beta5 and, while file access is far too slow to be usable right now, updating my above command to point to the new private ssh key allows the solution to work just as flawlessly as on the nfs-based dlite.

**Comment by TomFrost** [comment]
For folks who want to trial this approach on dlite 1.x, see my fork of fsevents_to_vm here: https://github.com/TechnologyAdvice/fsevents_to_vm. The fork includes a LaunchAgent that will monitor your home folder on startup and forward inotify events to the dlite vm. See the instructions added to the README.

**Comment by nlf** [comment]
added to the checklist in #145 so i'm going to close this issue, i have something that works and just needs some cleanup

**Comment by TomFrost** [comment]
Fantastic, looking forward to it! Many thanks.
