### ISSUE TITLE
Can't allocate a sparse image bigger than the free space

### ISSUE THREAD

**Issue by FiloSottile** [nlf/dlite#168]
I have 50GB free, and I tried to make a 80GiB disk, and got the error

```
Not enough free space to allocate a 80GiB disk image
```

Since this is a sparse image, this is unexpected.

**Comment by nlf** [comment]
i'm not sure why you would _want_ to create a sparse image that could cause your disk to become full, but maybe i can add a flag to allow skipping the free space check. it's there to help protect users though, so it'll always be on by default.

**Comment by FiloSottile** [comment]
If I get low on space, I'll delete things because running my docker containers is more important than the movies on the Desktop, however it's nice to have the movies, too.

I disagree that it offers any meaningful protection, because the disk can become full AFTER the image was created. There needs to be (sort of) graceful handling of out-of-space anyway when using sparse, and once you have that, I don't see why keeping this limit.

**Comment by nlf** [comment]
i removed this check because i agree it's not all that helpful
