### ISSUE TITLE
embed a DNS server

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#173]
by embedding a dns server in the daemon process we'll be able to eliminate the need to modify `/etc/hosts`, rather we'll create a resolver entry in `/etc/resolvers/` for the vm's domain that refers to our server.

in addition to making this lookup more reliable than a hard coded ip, it also means that this server can listen to the docker api within the vm and create dns entries for each running container as well. this combined with seamless routing should make using both the vm and containers from your host _very_ simple.

the down side to this is that it does likely mean we'll have to remove the ability to specify your own hostname for the vm so as to not break things. instead i will likely hardcode the domain as either `.dlite` or `.docker` (though i'm open to other suggestions here, so long as they don't overlap with real TLDs or other common dev tools)

**Comment by SerialVelocity** [comment]
There's a problem with this solution. /etc/resolvers is not read when you aren't connected to a network connection. This is important for offline dev work which is one thing that docker makes so easy.

**Comment by nlf** [comment]
hey, we have one of these now.

also i confirmed that the resolver works just fine when you're not connected to a network
