### ISSUE TITLE
docker commands stuck with connection refused / hijacked connection error.

### ISSUE THREAD

**Issue by mhubig** [nlf/dlite#174]
Hi I just installed `dlite` master via homebrew. But unfortunately all docker commands are hanging forever:

```
$ brew install --HEAD dlite
$ sudo dlite install
Would you like to continue? (Y/n): y
Building disk image: done
Downloading OS: done
Generating SSH key: done
Writing configuration: done
Creating launchd agent: done
$ dlite
DLite configuration:
  uuid           : 90854ebb-0547-11e6-a812-20c9d07d36cb
  cpu count      : 4
  memory         : 2 GiB
  disk size      : 20 GiB
  hostname       : local.docker
  dns server     : 192.168.64.1
  docker version : 1.11.0
$ dlite start
Starting the agent: done
The VM may take some additional time to fully boot
$ docker ps
--> hangs forever <--
```

Also if I stop `dlite`, the `dlite daemon` keeps running:

```
$ pgrep -lf dlite
29238 /usr/local/Cellar/dlite/HEAD/bin/dlite daemon
$ dlite stop
Stopping the agent: done
$ dlite stop
Stopping the agent: ERROR!
The agent is already stopped
$ pgrep -lf dlite
29238 /usr/local/Cellar/dlite/HEAD/bin/dlite daemon
```

If I manually start the `dlite daemon` I get an `connection refused / hijacked connection` error on every docker command.

```
$ sudo dlite daemon
COM1 connected to /dev/ttys002
rdmsr to register 0x34 on vcpu 0

dial tcp 192.168.64.8:2375: getsockopt: connection refused
2016/04/18 11:35:22 http: response.WriteHeader on hijacked connection

dial tcp 192.168.64.8:2375: getsockopt: connection refused
2016/04/18 11:35:43 http: response.WriteHeader on hijacked connection
```

I initially thought this could be the same problem as in #160, but downgrading to `dhyve-os` version `3.0.0-beta4` didn't fix the issue for me.

**Comment by nlf** [comment]
the master branch is in a state of huge amounts of flux so bugs can be expected. this sounds like something in the init scripts in the vm failed, i suspect it was the mounting of the file share.

if you're using the `master` branch of dlite are you also using the correct beta version of the os? it's marked as a pre-release so you have to ask for it manually. see the top of issue #135 for details

**Comment by mhubig** [comment]
I think I found a part of the problem: There is **no** docker binary in DhyveOS 3.0.0-beta4, just a 0-Byte file with the name /usr/bin/docker.

```
$ screen /dev/ttys004
DhyveOS
dlite login: root
Password:
DhyveOS version 3.0.0
# ps ax |grep docker
# ls -al /usr/bin/docker
-rwxr-xr-x    1 root     root             0 Apr 18 17:34 /usr/bin/docker
```

After manually installing docker into DhyveOS my local docker command works again! I think this is related to nlf/dhyve-os#27 ...

**Comment by danquah** [comment]
Try switching dhyveos to using a public dns-server - that has fixed that specific issue for me. Ie. `dlite config` and then update the dns-entry from 192.168.64.1 to some public dns-server, eg googles at 8.8.8.8

**Comment by nlf** [comment]
ah, this is because docker changed how downloads are packaged and the init script isn't able to work with the new way just yet. i'm working on it.

**Comment by nlf** [comment]
this is resolved in master branches and is pending release of dlite 2.x

**Comment by pyro2927** [comment]
Just making a note that this also kills the ability to `docker login` to a local/enterprise hub registry w/ private DNS.  Looking forward to the 2.x release, thanks for this project @nlf!
