### ISSUE TITLE
After updating local docker client I'll get error about version mismatch

### ISSUE THREAD

**Issue by onnimonni** [nlf/dlite#175]
Hey!

I have docker client installed with `$ brew install docker`

I believe this started when I ran `$ brew upgrade`. I have dlite setupped and I can ssh into it. But I can't run anything

```
$ dlite ip
192.168.64.4
$ docker ps -a
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
```

I can fix this problem by running: `$ brew switch docker 1.10.3`

Can I update docker version used in dlite?

**Comment by pgoltsev** [comment]
I have the same issue. Is there any workaround? I've downgraded the docker client version to 1.10.x and this solved the problem for now.

**Comment by nlf** [comment]
if you're talking about dlite 1.1.5, then just run `dlite stop && dlite update -v 2.3.0 && dlite start`

**Comment by onnimonni** [comment]
Thanks for quick answer! What happens if I only run `dlite stop && dlite update && dlite start` without the version?

**Comment by nlf** [comment]
currently, due to an incorrect assumption i made a while back, you'd still be on version 2.2.0. you have to specify the version as of now to make sure you're getting the newest. i'll try to push out a new 1.x release with this patched soon

**Comment by onnimonni** [comment]
Thanks, this solved it for me!

**Comment by nlf** [comment]
closing this, not going to bother patching dlite 1.x, 2.x is getting much closer

**Comment by xdumaine** [comment]
This is no longer fixing the problem for me. Any ideas?

**Comment by xdumaine** [comment]
Ahh, I see what happened - if anyone else is getting this - 

`brew switch docker 1.11.2` first, to get back from 1.24 to 1.23.

Side note: these version numbers make no sense whatsoever. Need dlite 1.1.5 with version 2.3.0 (of what?) to match with docker version 1.11.2, which is using version 1.23 (which is what?)

**Comment by nlf** [comment]
yeah, the versions are confusing :/ docker's api versions don't match the actual release versions, and dlite's (and the os) versions don't match the docker versions so it can get pretty hairy trying to figure out what goes where
