### ISSUE TITLE
docker-compose + dlite

### ISSUE THREAD

**Issue by ycherfan** [nlf/dlite#183]
Hi! Is it possibile to use docker-compose with dlite? I can't find docker-compose inside dlite virtual machine and when I run docker-compose outside dlite it prints the message: "ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`."

**Comment by residentsummer** [comment]
Yes, it is possible to use docker-compose with dlite. That error message suggests that there is something wrong with your setup - docker-compose is trying to connect to docker by wrong address. Maybe you have `DOCKER_HOST` env var left from docker-machine? Try this:

```
unset DOCKER_HOST; docker ps
```

If it's working, docker-compose should work as well.

**Comment by ycherfan** [comment]
Problem solved. Thanks!

On May 2, 2016, at 1:52, Anton S notifications@github.com wrote:

Yes, it is possible to use docker-compose with dlite. That error message
suggests that there is something wrong with your setup - docker-compose is
trying to connect to docker by wrong address. Maybe you have DOCKER_HOST
env var left from docker-machine? Try this:

unset DOCKER_HOST; docker ps

If it's working, docker-compose should work as well.

**Comment by residentsummer** [comment]
You're welcome! Please consider closing the issue if it's resolved :)

**Comment by nlf** [comment]
closing it, thanks for the assist @residentsummer
