### ISSUE TITLE
docker-squash within dlite

### ISSUE THREAD

**Issue by jjude** [nlf/dlite#185]
I'm trying to install & use docker-squash within dlite. For installation, I need to do this:

```
wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
```

This gives me an error:

```
wget: can't execute 'ssl_helper': No such file or directory
```

I downloaded from within Mac Shell / unzipped & untared and from within dlite, moved to `/usr/bin`

But when I use `docker save <image id> | sudo docker-squash -t newtag | docker load`, it gives me an error:

`tar: unrecognized option`--same-owner'`

Is it possible to update the tar binary to use all options? How to do it? Or otherwise anyone used docker-squash within dlite?

**Comment by nlf** [comment]
as far as i'm aware docker-squash doesn't need to be installed in the vm, you can just run it from your host operating system. reopen this issue if i'm wrong, but i'm pretty sure on this one.
