### ISSUE TITLE
ssh connection timed out

### ISSUE THREAD

**Issue by rcholic** [nlf/dlite#186]
I just installed `dlite` on my Mac OSX using the Go source, but I got the following error when I do ssh connection: `ssh root@local.docker` in the terminal (I make sure I started dlite: `dlite start`):

```
ssh: connect to host 192.168.64.2 port 22: Operation timed out
```

The version of dlite installed is 2.3.0, and I provided my ssh-key file explicitly in the installation:

```
sudo dlite install -v 2.3.0 --ssh-key=/Users/username/.ssh/id_rsa.pub
```

**Comment by nlf** [comment]
if you run `ps aux | grep dlite` do you see a process running? did you try waiting 5 minutes after you start the vm? sometimes it can be a little slow to boot the first time

**Comment by rcholic** [comment]
the output of `ps aux | grep dlite` indeed shows the process is running. Even after waiting for 20 minutes, I still get the timed out error for ssh connection. There got to be something wrong, I am sure no other virtual machines are running on the same machine. Thanks @nlf

**Comment by nlf** [comment]
closing this due to new beta being released, if it happens there feel free to open a new issue https://github.com/nlf/dlite/releases/tag/2.0.0-beta7
