### ISSUE TITLE
New version soon?  Having trouble with the old version.

### ISSUE THREAD

**Issue by synic** [nlf/dlite#188]
I've been using 1.1.5 for a while now, and it's awesome.  Much much faster and less buggy than the official Mac beta client.

For most things.  There are a few docker setups that just don't work in dlite, but they work in the mac beta client.  So now I'm running both, and it's pretty irritating.

I'm wondering if the 2.0 beta will fix it and then I can just use dlite again, but it seems like movement has stopped.  Will you still be working on it now that the mac beta exists?

**Comment by nlf** [comment]
I'm absolutely still working on it, it's just taking me some time trying to fix a few things the right way to make it as flexible and reliable as possible. I'm getting close though!

**Comment by orefalo** [comment]
+1 really cool project, love working with docker ever since.

BUT.. would love to see docker 1.11.2 support

**Comment by orefalo** [comment]
Actually

```
dlite stop
dlite update -v 2.3.1
dlite start
```

fixed my issue! plz update docs!

**Comment by dmlemos** [comment]
@orefalo It actually seems to add DOCKER_API_VERSION=1.22 to the shell. Which was a way to fix dlite with the new docker.

**Comment by nlf** [comment]
https://github.com/nlf/dlite/releases/tag/2.0.0-beta7
