### ISSUE TITLE
Make hostname configurable

### ISSUE THREAD

**Issue by leipert** [nlf/dlite#19]
Hey there, I love your tool. It's dlite-ful.
In a bunch of projects we use a different host alias (`docker.local`).
Could you make the alias somehow configurable? I know it would be a small fix, but I am not too fit with go :+1:

**Comment by nlf** [comment]
yup, making the hostname configurable is a great idea. i'll work on that

**Comment by ruimarinho** [comment]
That'd be cool. Parallels uses `<machine>.shared`, which might be interesting to emulate in case a work environment uses both tools.

**Comment by silvamerica** [comment]
I am adding my support to a configurable hostname. I use .dev, which has it's own issues but I already have it in a lot of code.

**Comment by silvamerica** [comment]
:tada: Thanks!
