### ISSUE TITLE
Docker commands hang indefinitely without output

### ISSUE THREAD

**Issue by herrbischoff** [nlf/dlite#190]
## Issue

I have installed `dlite` (1.1.5) via Homebrew and it used to work fine on my machine. Recently (I'm unable to pinpoint it, probably after the 10.11.5 update), it stopped working for me. Running any `docker` command like `docker info` results in an indefinite hang until I abort.

Installing the `HEAD` version via Homebrew results in error, downloading the 2.0.0-beta5 and replacing the Homebrew-installed binary works but does not change the behavior. I have also completely uninstalled `dlite` and reinstalled it, without any luck.
## Environment

```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.5
BuildVersion:   15F3
```

```
❯ dlite version
2.0.0-beta5
```

```
❯ docker version
...hangs...
```

**Comment by herrbischoff** [comment]
Hi @nlf! Is there any news on this or are you currently not actively working on `dlite`?

**Comment by nlf** [comment]
i'm still working on dlite, but i do so after i work a full time job so it's not exactly a fast pace most weeks. i have made a bit of progress lately, but after making a mess of my own code i had to slow down and think more about how i want the pieces to fit together.

i promise a new version is coming, i can't promise _when_ it's coming though. hopefully soon.

**Comment by herrbischoff** [comment]
No worries! I know that work takes a major chunk of ones' time and energy. I'm looking forward to see what you come up with on _your_ time. Thanks for taking the time to respond and for creating dlite in the first place!

**Comment by eden** [comment]
@herrbischoff I ran into this recently when I had my local firewall set to block all incoming connections. Unsetting that option made things work again. Can't guarantee that's what's happening to you, but the system logs (from the Console app) may help pinpoint the problem.

**Comment by bjeanes** [comment]
Try running `sudo dlite daemon` (after `dlite stop`ping it). I was also having this but it didn't start working until I manually saw the daemon boot back up. `dlite start` correctly brought up the daemon for me and it was working again.

FWIW, I am running 1.1.5 but with a newer image (`dlite install -v 2.3.0`). In my case, installing a newer version of the image took the error from a client version mismatch to the hanging. I think I must have had an old VM that didn't shut down properly or something else that was preventing the new one from booting and being available.

Hope that helps in some fashion until @herrbischoff has a more permanent solution with his current WIP...

**Comment by herrbischoff** [comment]
Thanks everyone for your suggestions. Since the official Docker for Mac is far more integrated into macOS (still an ugly spelling...) now, I stopped using `dlite` altogether and switched full-time to Docker.app.

**Comment by bjeanes** [comment]
Aww... too bad. `dlite` is _such_ a nicer solution IMO, but I understand not wanting to duplicate efforts.

May I suggest updating the `README` on the default branch so that others can find that info quickly?

**Comment by nlf** [comment]
i promise a new version _is_ coming, i've been short on time lately but i am working on it.

**Comment by bibendi** [comment]
Currently docker for mac is not useable https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/142

**Comment by santagada** [comment]
I only got it to work without restarting my machine with a combination of "sudo dlite daemon" and using "brew install homebrew/versions/docker110" docker 1.11 or dlite start didn't work with dlite install -v 2.3.0

**Comment by santagada** [comment]
apparently that linux image has docker 1.10 inside it, not 1.11 as is the default on hombrew right now

**Comment by nlf** [comment]
https://github.com/nlf/dlite/releases/tag/2.0.0-beta7 new beta, remove your old versions before trying it!
