### ISSUE TITLE
Client is on Version 1.24

### ISSUE THREAD

**Issue by azngeek** [nlf/dlite#193]
Hello, is there a way to update the docker server to 1.24 from 1.23? I have installed dlite on my new machine and used brew which only installs client verison 1.24

**Comment by getninjaN** [comment]
Try adding `DOCKER_API_VERSION=1.23` to your environment variables.
It worked for me.

Peace!

**Comment by bpinto** [comment]
You could build your own image. There is an open PR upgrading docker server to latest [here](https://github.com/nlf/dhyve-os/pull/33).

**Comment by nlf** [comment]
https://github.com/nlf/dlite/releases/tag/2.0.0-beta7

brand new beta, resolves this problem
