### ISSUE TITLE
VM unresponsive on macOS Sierra

### ISSUE THREAD

**Issue by TomFrost** [nlf/dlite#194]
On a fresh install of macOS Sierra + Homebrew:

```
brew install dlite docker # Installs dlite 1.1.5 and docker 1.12.1
dlite install -v 2.3.1
dlite start
# Wait a minute
dlite ip
```

Output: `Failed to find an IP for the virtual machine in 15 seconds`

Running `docker ps` throws out the usual `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

I've never touched xhyve and am at a loss for where to start debugging this. Docker for Mac fails miserably for my application, so I'm very interested in getting this functional.

**Comment by nlf** [comment]
I haven't actually tested in sierra just yet, I plan to update today sometime and I'll take a look and see if it's even compatible

**Comment by tamasimrei** [comment]
I'm having the same issue. The dlite process starts up, then exits without any feedback or error.
Is there a way to get some log info? I'm not a go developer, but know a thing or two about software development and system administration, maybe I could help a bit.

**Comment by nlf** [comment]
so i've updated and confirmed this is definitely a sierra related bug, i'm working on getting it fixed

**Comment by tamasimrei** [comment]
Thanks! Appreciate you're looking into it this urgently. Hope it's something quick to fix, I need this thing more than ever now.
Working on a database migration, and Docker for Mac runs slow like hell, and symfony keeps losing connection to the MariaDB docker instance.

**Comment by TomFrost** [comment]
@tamasimrei Since you need it urgently, there's also [Dinghy](https://github.com/codekitchen/dinghy) which is gives you a similar end-result to dlite, but is a layer on top of docker-machine (which you can use with xhyve like dlite does for better native performance). Alternatively, you could just run docker-machine with the xhyve provider yourself, then run the [docker-machine-nfs](https://github.com/adlogix/docker-machine-nfs) script to switch it over to NFS shares instead of the default solution.

I think dlite's a head above those options due to the custom xhyve OS and local socket file rather than needing a slew of environment variables for a remote TCP connection, but they work well in a pinch.

**Comment by tamasimrei** [comment]
@TomFrost thanks, will check them out!

**Comment by ErikZigo** [comment]
Hi is here any update for this issue? We have same problems on Siera.. We tried some alternatives, but they are not working too.

**Comment by nlf** [comment]
i have a fair amount of work done in the refactor branch here that i'm still doing some testing with. it's rough and probably needs some debugging, but it's mostly functional. give me another day and i'll release a beta

**Comment by kowoba** [comment]
Why does it work just fine for me? :)

**Comment by luchianenco** [comment]
waiting for beta =)

**Comment by nlf** [comment]
https://github.com/nlf/dlite/releases/tag/2.0.0-beta7

please remove any previous installations you had before trying it. i'm going to clean up existing issues, so feel free to open new issues for any problems you have.
