### ISSUE TITLE
Benchmarking performance

### ISSUE THREAD

**Issue by ruimarinho** [nlf/dlite#20]
Let me start by saying that this project has been an extremely pleasant surprise as an OSX user of docker. Thank you for your effort in publishing this tool.

I have run a couple of projects using dlite and a non-scientific method currently shows that it is about 30% slower than a VM running boot2docker with Parallels 11 (via docker-machine). I was under the impression that Hypervisor.framework would yield better results, but apparently that is not the case on my setup.

These tests do not use the NFS mounted folders - pulling an image and starting a container results in the same performance difference.

Is there any tuning available or is this the expected outcome for now?

**Comment by nlf** [comment]
as of now, this is expected and only minimal tuning is available (when you install you can tell DLite how many CPUs to use and how much of your ram it can access, after installation you can edit the `~/.dlite/config.json` file and change those values and restart DLite if you like).

beyond that, [xhyve](https://github.com/mist64/xhyve), the library that dlite is based on is still a work in progress and as such has some room for improvement. there is a todo list on the xhyve readme that details the things that could be changed to increase performance. until those items are resolved, dlite will be slightly slower than other virtualization solutions.

the good news is i pay pretty close attention to changes to xhyve, and plan on building against them so we should see steady improvements over time.

**Comment by ruimarinho** [comment]
Thanks, I've updated the cpu count to see if it brings any improvement. I'll keep an eye on xhyve too.

**Comment by nlf** [comment]
ram plays a pretty big part in performance too, i like to run with at least 3gb (though i kept the default at 1) so you might also try playing with that
