### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by arnested** [nlf/dlite#202]

**Comment by arnested** [comment]
The build instructions for the master branch doesn't work for me (and @danquah).

We end up at

``` sh
% go generate
make: *** No targets specified and no makefile found.  Stop.
gen_assets.go:4: running "make": exit status 2
```

**Comment by nlf** [comment]
ah, i suspect the main thing i'm missing is initializing the submodule. run

```
git submodule init
git submodule update
```

then try again

**Comment by arnested** [comment]
Indeed. Thanks.

See PR #203.
