### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by leipert** [nlf/dlite#23]
I do not know whether you have made any thoughts on better install / update strategies. I am trying to get dlite into homebrew: https://github.com/Homebrew/homebrew/pull/48460

My only question is whether it should show a message after installation that you have to run `sudo dlite install` or `sudo dlite update`:

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/youtube-dl.rb#L33-L35

**Comment by btaylor** [comment]
I had a similar thought, but I went down the path of creating a cask for dlite (https://github.com/caskroom/homebrew-cask/pull/17487).  I decided to make `sudo dlite install` a user action, as they may want to configure the size of the machine image, number of CPUs, etc.

**Comment by nlf** [comment]
@btaylor left you a comment on the cask pull request, but other than that it looks good and i think that'll be good enough for most? a full on homebrew formula might be nice too for people that want to track the master branch i guess. i dunno, i didn't really put that much thought into it

**Comment by nlf** [comment]
i'm going to close this since @leipert has already made the pull request to homebrew (thanks for that btw!)
