### ISSUE TITLE
"could not find image: no such id" after reboot

### ISSUE THREAD

**Issue by jakajancar** [nlf/dlite#25]
I'm getting the following after reboot, for images that have already been downloaded:

```
$ docker run --rm -it debian:jessie
Error response from daemon: could not find image: no such id: 7a01cc5f27b11937f3ed7c8a42e049eb96b23520d9989e1759fcac8c9864264d
```

If I run it as "debian:latest" (which points to the same image), it forces a download and then even "debian:jessie" starts working.

Any ideas?

**Comment by nlf** [comment]
interesting.. what's the output of `docker images` after a reboot?

**Comment by jakajancar** [comment]
Empty, also with -a. Let me try a reinstall and repro again, also after OS X upgrade.

**Comment by jakajancar** [comment]
After upgrading OS X to 10.11.3, wiping all dlite's data and upgrading it to 1.0.4, this now works. Not sure what fixed it... :/
