### ISSUE TITLE
Sync changes?

### ISSUE THREAD

**Issue by ericclemmons** [nlf/dlite#31]
I apologize if I'm way off base here.

The last time I tried to use docker for local development, the biggest issue was that file changes weren't picked up on by the VM/Docker.

Is that solved here with the NFS mounting?

e.g. Can Gulp/Grunt/Webpack/Watchify see a change on ~/My/Project/index.js and rebuild?

**Comment by CedricGatay** [comment]
Basically `inotify` does not work through NFS, so your tool need to fallback to polling. One way of mimic'ing `inotify` would be using mac os equivalent to `inotify` (`fswatch`) and touch'ing the files in the underlying linux to trigger the `inotify` event.
I don't know the impact on performances of `fswatching` a lot of files.

**Comment by ericclemmons** [comment]
Makes sense.  Thanks!

**Comment by Coobaha** [comment]
@ericclemmons you can use https://github.com/brikis98/docker-osx-dev
