### ISSUE TITLE
Choose default disk size to that of Docker-Machine's

### ISSUE THREAD

**Issue by djui** [nlf/dlite#34]
This helps to reduce friction for new users by being as close as possible to Docker's defaults.

Just a suggestion, and arguable debatable how similar it needs to stay and if _their_ default is maybe outdated.

**Comment by nlf** [comment]
sure, i can reduce it to the 20GiB that it appears docker-machine defaults to. that's likely reasonable.

**Comment by drewcrawford** [comment]
Could we raise memory to 2GB to match docker-machine as well?  I hit this earlier trying to move to dlite.

**Comment by nlf** [comment]
seems reasonable to me
