### ISSUE TITLE
Specify custom shared directory instead of /Users

### ISSUE THREAD

**Issue by darklow** [nlf/dlite#36]
I tried running one app in docker and by changing locally files on docker container were synced after 4-5 seconds. (SATA disk). 

I guess exporting whole `/Users` is the issue here, just too many files. I have millions of files in my /Users directory because of many years of previous development, python virtualenvs etc. However I use docker only for some projects.

If I could specify other path rather than `/Users` I could possibly get huge speed improvement in sync.

PS. Thanks for the awesome tool. Finally I can use docker on OSX, i gave up on all the previously available methods.

**Comment by caarlos0** [comment]
+1

**Comment by nlf** [comment]
certainly doable, will make a note. i can also change the default to share only the current user's home, which wouldn't solve your issue but may help avoid this for other people. thanks for bringing it up!

**Comment by JoyceBabu** [comment]
+1. I am also really interested in this feature, as I keep all my docker files in `/opt/docker`.

**Comment by nlf** [comment]
actually going to keep this open for right now because this depends on a matching change in dhyve-os to allow mounting a different directory

**Comment by nlf** [comment]
ok.. now this is correct :) you'll likely want to uninstall and install again to make sure you get the updated OS pulled in as well as the new config
