### ISSUE TITLE
Why ~/.dlite

### ISSUE THREAD

**Issue by caarlos0** [nlf/dlite#37]
I think the right place to put stuff is `~/Library/Caches/dlite` and `~/Library/Application Support/dlite`...

I did the same for one of my apps, so there is even a lib for it, if you want: https://github.com/caarlos0/gohome

Cheers

**Comment by kitten** [comment]
That seems inconsistent with applications like docker and docker machine, which use `~/.docker`. It's quite the default on Unix platforms I'd say.

**Comment by caarlos0** [comment]
I think the default is to follow XDG: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nlf** [comment]
yeah my choice was based on what docker-machine does, i think moving the files is a bit nit picky though and unless there's a valid reason outside of OS X convention for doing so i'm not going to bother

**Comment by caarlos0** [comment]
Ok.
