### ISSUE TITLE
Joint force?

### ISSUE THREAD

**Issue by Gnep** [nlf/dlite#4]
Hi there,

I've been working on xhyve in [Hyper](github.com/hyperhq/hyper). The current Mac version uses Vbox, but the community prefers xhyve. Wanted to ask whether you are interested in the join the effort?

Best,
Peng

**Comment by musha68k** [comment]
Hi Gnep,

not adding much to this issue in particular but the link was garbled-up a bit, so here is the working reference: [Hyper](https://github.com/hyperhq/hyper). Btw I'm currently evaluating dlite but didn't know about Hyper so thanks!

**Comment by Gnep** [comment]
@musha68k 

Thanks!

Hyper is a hypervisor-agnostic Docker runtime. So we want to add xhyve support. Someone is porting qcow2 to xhyve. So it is excisting to see more and more efforts around the new hypervisor.

**Comment by nlf** [comment]
hyper does quite a bit more than i intend to do with this project.. i'm gonna close this, but do feel free to mention me in issues in hyper if you'd like my input. i'm happy to help where i can.
