### ISSUE TITLE
CLI to get vm IP

### ISSUE THREAD

**Issue by clkao** [nlf/dlite#44]
like what `docker-machine ip <machine>` does

**Comment by arnested** [comment]
`dscacheutil -q host -a name local.docker`

**Comment by djui** [comment]
@arnested Or `grep local.docker /etc/hosts` but both are only convenient until the hostname will change as a newly introduced parameter to `dlite install --hostname X`. Then the daemon basically knows the IP and a simple `dlite ip` is again convenient.

**Comment by arnested** [comment]
Yes, your are probably right.

**Comment by nlf** [comment]
i can add a command for this
