### ISSUE TITLE
Can't ssh to docker@local.docker

### ISSUE THREAD

**Issue by mnishizawa** [nlf/dlite#48]
According the the README, I should be able to ssh to docker@local.docker.  I'm assuming it uses the ssh key I specified during the install but it asks for a pw.

**Comment by nlf** [comment]
did you use an ssh key other than the default? if so, how did you specify the path?

**Comment by mnishizawa** [comment]
I tried it both ways.  When I specified the key I did:

```
sudo dlite install --ssh-key=/Users/mnishizawa/.ssh/id_dsa.pub
```

**Comment by nlf** [comment]
interesting, i wonder if it's something to do with using a dsa key vs rsa. i'll see what i can find

**Comment by mnishizawa** [comment]
I did uninstall and install several times using several different options and I also tried specifying an rsa key as well as letting it use the default.  I got the same result.

**Comment by emaiax** [comment]
I'm having the same problem here.

**Comment by nlf** [comment]
can you log in as `root@local.docker` with the password `dhyve` and check for a `.ssh/authorized_keys` file in the docker user's home directory?

**Comment by emaiax** [comment]
I couldn't login with `dhyve` password :/

``` sh
~ $ dlite ip
192.168.64.3
~ $ ssh root@local.docker
The authenticity of host 'local.docker (192.168.64.3)' can't be established.
RSA key fingerprint is 61:08:7e:6c:27:aa:77:32:ce:d4:d5:4c:9d:8b:8c:f9.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'local.docker,192.168.64.3' (RSA) to the list of known hosts.
root@local.docker's password:
Permission denied, please try again.
root@local.docker's password:

~ $
```

**Comment by mnishizawa** [comment]
No, that did not work.

**Comment by mnishizawa** [comment]
Closing the issue.  I removed the version that I got from go get and installed using the homebrew package and now this is not an issue.  Perhaps it is a common mistake that happened during the build process.

**Comment by emaiax** [comment]
I still got the problem. :/

**Comment by prigal** [comment]
Hey, I had the same issue. 

Reinstalling dlite from binary with ssh-key option and docker from brew solve the problem for me.

**Comment by emaiax** [comment]
After reinstalling everything, it started to work using `docker@local.docker`, even without the ssh-key. :+1: 

Except for `root@local.docker` with `dhyve` password.

``` sh
~ $ ssh root@local.docker
root@local.docker's password:
Permission denied, please try again.
root@local.docker's password:
Permission denied, please try again.
~ $
```

**Comment by zapient** [comment]
Seeing same issue as of today using latest build from master

**Comment by kikokikok** [comment]
same here tried with brew & latest 2.0 beta 5 
both are failing on login with docker & root

**Comment by nlf** [comment]
the latest betas are just that, beta. there's a good chance you'll find bugs.

the latest version in homebrew, 1.1.5, _should_ work ok. if it doesn't odds are you've just stumbled across a bug. i'm working on making this stuff as robust as i can, but it's a long road. the next beta of 2.0 should be quite a bit better.

**Comment by kikokikok** [comment]
well brew is the 1.1.5 and I haven't been able to make it work so far. I'll continue checking

**Comment by hutchike** [comment]
FYI I'm seeing this same issue with 2.0.0-beta5 (downloaded the binary, running on Mac OS X 10.11.5, Docker version 1.10.3):

```
$ ssh docker@local.docker
docker@192.168.64.2's password:
```

**Comment by aleemb** [comment]
This should work `ssh docker@local.docker`

**Comment by eden** [comment]
for anyone finding this issue via google. I got it to work with 2.0.0-beta8 by specifying the key that's saved to `~/.dlite/key`:

```
ssh -i ~/.dlite/key docker@$(dlite ip)
```
