### ISSUE TITLE
Unable to chown on mounted volume

### ISSUE THREAD

**Issue by 14to9** [nlf/dlite#50]
Hi Nathan,

Love love this project so far.  Trying it out today on our nine container (locally docker-compose'd) project has everything running amazingly smoothly (and so much faster IO than VirtualBox thankyouverymuch) 

BUT

One issue is this:  On our simulated ftp host, the container we're running attempts to run `chown` on the mounted path and fails.  Here's the step to reproduce (requires a local directory to test with, can be empty):

``` bash
$ docker run -v /Users/14to9/dev/project/ftp:/ftp -it -e USERNAME=a -e PASSWORD=b morrisjobke/docker-proftpd:latest 
Setting credentials to a:b
chown: changing ownership of '/ftp/abcbwi-1438018428_20150727-173347_204.xml': Operation not permitted
chown: changing ownership of '/ftp': Operation not permitted
$ 
```

Is this expected behavior from dlite, or the permissions issue it feels like?

Thanks again for this project :+1: :100:

**Comment by nlf** [comment]
so those chown steps would actually be running on an nfs mount which enables root_squash by default to protect your files. i'll have to see if i can tweak the nfs export config to allow for this.

**Comment by emaiax** [comment]
I guess I'm having the same issue trying to mount postgresql with a persistent data volume on my `/Users` path.

``` sh
/Code/db $ docker run --rm -v "/Users/emaiax/Code/db/data:/var/lib/postgresql/data" postgres
chown: changing ownership of ‘/var/lib/postgresql/data’: Operation not permitted
```

I don't know if it's the same issue, let me know if I'm on the wrong place.

**Comment by nlf** [comment]
if you edit `/etc/exports` and change the `-mapall=##:##` (where ## will be your UID and GID) to `-maproot=root:wheel` does this resolve the issue for both of you?

**Comment by nlf** [comment]
oh, note that after doing that you'll have to run `sudo nfsd update` and then `dlite stop && dlite start` for the change to take effect

**Comment by arnested** [comment]
Changing `/etc/exports` as described here and the change from #69 finally made me run MariaDB-containers with `/var/lib/mysql` on a volume!

:+1:

**Comment by emaiax** [comment]
Yeah, that works like a charm! :dancers:

**Comment by 14to9** [comment]
Thanks, Nathan!

👍🏼
