### ISSUE TITLE
Awesome start, but could be even easier :)

### ISSUE THREAD

**Issue by atomantic** [nlf/dlite#51]
This is more of a comment to the blog post than an issue.

Someone asked for a TLDR of your blog post and while the value proposition summary is easy to grok:

a little helper daemon (DLite) written in Go that;
- eliminates the need export env setting using eval
- emulates /var/run/docker.sock so docker client can talk to the vm
- adds local.docker to the hosts file for easy consumption (ssh docker@local.docker)

The setup instructions are more complex than needed (although a good start):
1. download go binary from here: https://github.com/nlf/dlite/releases 
2. `chmod 755 ~/Downloads/dlite`
3. `mv ~/Downloads/dlite /usr/local/bin/` or somewhere else in your PATH
4. `sudo dlite install`
5. `dlite start`

That's 5 steps... why not just `brew install dlite && dlite start` or `go get dlite && dlite start`?

Everything is better if it can be reduced to command line instructions. People (and instructions) get lost when a step includes visiting a website to download something and then putting that thing somewhere manually. Even for savvy people :)

Great project!

**Comment by nlf** [comment]
it might be possible to change the homebrew formula to run the installer for you, but i'm not sure how they feel about letting you run commands with sudo

**Comment by nlf** [comment]
let's move this discussion to https://github.com/Homebrew/homebrew/pull/48460
