### ISSUE TITLE
Sharing Directories with docker image

### ISSUE THREAD

**Issue by pfortin-urbn** [nlf/dlite#53]
Is there a way to share directories between the Host and the dlite VM?  I want a mongo host where the DB files reside on my Mac.

**Comment by nlf** [comment]
by default your entire `/Users` directory is available in the VM via an NFS mount, so any directory in there  can be mounted as a volume in your docker containers

**Comment by nlf** [comment]
there is now also a `-S` or `--share` flag that allows you to specify a different path to mount when you run the installation

**Comment by pfortin-urbn** [comment]
:+1:   Thanks!!!

**Comment by ondrejhlavacek** [comment]
How is this achievable now? I'm having difficulties accessing folders/files in `/var`.
