### ISSUE TITLE
Sparse disk support

### ISSUE THREAD

**Issue by dunkelstern** [nlf/dlite#55]
Hi,

I have implemented sparse disk support, i can't currently make a pull request because i changed some imports to direct to my github versions of libxhyve and dlite/utils but if there is interest i can rework a branch to include only the needed changes.

Just let me know

**Comment by nlf** [comment]
@dunkelstern which method did you use for sparse disks? the raw disk support? if so, that should be available in the libxhyve branch that i'm using

**Comment by dunkelstern** [comment]
No it's a custom implementation that writes to a set of files so you don't have to mount a sparse bundle in the os. I am currently working on a tool that allows shrinking the sparse disk after it was filled and in turn emptied again.

See http://blog.dunkelstern.de/2016/01/16/xhyve-lightweight-vm-for-mac-os-x/ for details, you may skip the first two sections as you already know what xhyve is ;)

**Comment by nlf** [comment]
i think i'm more interested in the raw disk support, so i'm going to decline on this

**Comment by dunkelstern** [comment]
Ok no problem, i will maintain my patchset in my repository. Just added TRIM support and automatically shrinking sparse disks. Had to heavily refactor the `block_if.c` though.
