### ISSUE TITLE
Not able to run dlite

### ISSUE THREAD

**Issue by iler** [nlf/dlite#56]
I'm having problems using dlite as it seems that either it does not install correctly or it does not run properly for some reason. When running **sudo dlite install** it does not ask for sudo pass for some reason but it does not complain anything either. After install I run **dlite start** and I get no output so everything should be ok? However when running **dlite ip** I get "_Failed to find an IP for the virtual machine in 15 seconds._" Also running **docker ps** gives me "_Cannot connect to the Docker daemon. Is the docker daemon running on this host?_" I have tried uninstalling and removing everything. I have installed xhyve both from brew and from source. I'm running OS X 10.11.3. What could be wrong?

**Comment by Donavan** [comment]
I'm having the same issue on OSX 10.10.5

```
launchctl list | grep dlite
```

shows that local.dlite has exited with a status of 1 immediately after starting.

Is there a log somewhere to look at?

**Comment by Donavan** [comment]
Running dlite daemon gave me an error about my exports.   The README should probably indicate that the exports entry gets added when you run, not at install time.  When I looked at the file there was nothing from dlite so I didn't touch it.

Now I have to figure out how to run both dlite and vagrant.

**Comment by iler** [comment]
@Donavan thanks for the help. My problem was also because of some obsolete entry in /ext/exports. For my case as it was obsolete removing it fixed my problems. But if you find out the way of running both dlite and vagrant side by side I would be interested in hearing the solution as vagrant is widely used in our organisation.

**Comment by nicgrayson** [comment]
I was having this problem too. Deleting my `/etc/exports` worked.

**Comment by nlf** [comment]
that's a good point, i'll amend the note to make sure it's clear that the export is added at start and not at install time.

closing this issue
