### ISSUE TITLE
Unable to reach "local.docker" hostname after uninstall and upgrade

### ISSUE THREAD

**Issue by darklow** [nlf/dlite#57]
First install version of dlite was working perfectly and i could access docker containers through host `local.docker`

I uninstalled and installed new version of dlite to get custom shared folders feature.
And now docker is not available though `local.docker` hostname anymore.

What I did:

``` bash
$ sudo ./dlite uninstall
Removing launchd agent: done
Removing files: done

$ sudo ./dlite install --share=/Users/darklow/www/docker
Building disk image: done
Downloading OS: done
Writing configuration: done
Creating launchd agent: done
```

Now when i run my container it is not available through `local.docker` as before.
I also tried uninstalling and installing again specifically with --hostname param. But no luck as well.

``` bash
$ sudo ./dlite install --share=/Users/darklow/www/docker --hostname=local.docker
```

I also tried resetting my DNS with `sudo killall -HUP mDNSResponder` but no luck.

Any ideas what I should do?
Thank you.

**Comment by darklow** [comment]
I also tried:

```
$ sudo ./dlite ip
Failed to find an IP for the virtual machine in 15 seconds
```

These commands also give no output:

```
dscacheutil -q host -a name local.docker
grep local.docker /etc/hosts
```

However docker is running just fine

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
ffc28285c9a7        project_web         "python manage.py run"   2 days ago          Up 2 minutes        0.0.0.0:8000->8000/tcp    project
2d1d9d64c95b        redis               "/entrypoint.sh redis"   2 days ago          Up 2 minutes        0.0.0.0:32772->6379/tcp   project_redis_1
2371d76abce3        postgres            "/docker-entrypoint.s"   2 days ago          Up 2 minutes        0.0.0.0:5432->5432/tcp    project_db_1
```

**Comment by darklow** [comment]
More info to help you spot the problem:
If i run:

```
$ cat /var/db/dhcpd_leases
{
    name=3760cf7c-c3ff-11e5-8cb9-10ddb1b01b46
    ip_address=192.168.64.2
    hw_address=1,d6:85:7b:6a:cf:32
    identifier=1,d6:85:7b:6a:cf:32
    lease=0x56ab1d24
}
```

Then i can access docker by this IP adress: `192.168.64.2`

But if i check my `/etc/hosts` they there are no lines that should be added by dlite.
So i guess by some reason regexp for IP detection fails and is not written into `/etc/hosts`.

**Comment by nlf** [comment]
strange, i'll see if i can figure out why the hosts entry didn't get added.

can you do me a favor and check the Console app and see if you can find any errors coming from dlite?

**Comment by testn** [comment]
does not work for me either. It didn't try to modify `/etc/hosts`

Update: in my case, it looks like i have some existing `/etc/exports` file. If I delete the file and reinstall it again. It gets passed to the next point where `/etc/hosts` file get updated. However, the service still failed to start up. I had to `sudo touch /etc/exports` and then reinstall again to get it working.

**Comment by darklow** [comment]
@nlf I won't be able to check Console app for a few days (that was on my work mac).
However because `sudo ./dlite ip` doesn't work and `cat /var/db/dhcpd_leases` returns everything fine (i posted results from both commands in my previous comment) makes me think there may be something wring with the regexp pattern: 
https://github.com/nlf/dlite/blob/70a4a3bdb7bd6ba08d14634d433f62bc1902b049/utils/hosts.go#L33

**Comment by nlf** [comment]
you can see here that the regex works correctly for your entry https://play.golang.org/p/YsM99bhJLk

**Comment by nlf** [comment]
check the `~/.dlite/config.json` file to make sure the uuid there matches the one that you find in `/var/db/dhcpd_leases`

**Comment by imsky** [comment]
+1 - seeing the same issue after uninstalling. /etc/hosts isn't edited'

edit: `dhcp_leases` does NOT have the uuid from `~/.dlite/config.json`
edit 2: fixed after rebooting - leases shows the right uuid now

**Comment by nlf** [comment]
so @imsky everything is working ok for you now?

@darklow are you still having problems?

**Comment by imsky** [comment]
@nlf it only works after restart. uninstalling and reinstalling without a restart **does not** work

**Comment by nlf** [comment]
are you on dlite 1.1.3? it should be removing the old entry from the hosts file when you uninstall

**Comment by imsky** [comment]
yes

```
$ dlite version
1.1.3
```

**Comment by nlf** [comment]
ok, i'll do some more investigating. thanks

**Comment by imsky** [comment]
just replicated this with a few other engineers on install as well. seems a restart is needed even after install to get the entry working. some have also reported that no `/etc/hosts` entry was added and the VM still worked.

**Comment by pfortin-urbn** [comment]
I believe that I had this issue, I resolved it by doing:
1. sudo dlite uninstall
2. rm -Rf ~/.dlite
3. sudo dlite install

Let me know if that helped...

**Comment by nlf** [comment]
are people still having issues with this?

**Comment by cmosetick** [comment]
@nlf I know I already covered this in my proposal on #77, but I think dlite should consider skipping the entire `/etc/hosts` file entry because it can be messy with custom setups that people might have, and requires sudo.

The ssh config file proposal is all handled entirely in the users $HOME dir.

Also, while dlite installed correctly on my first go before the inclusion into homebrew, FWIW consider that my hosts file was 15367 lines long when I installed dlite. I'm guessing others have shorter hosts files, yet still had issues with the /etc/hosts entry. Just some thoughts.

**Comment by darklow** [comment]
@nlf Yes problem still occurs. I tried `dlite` on another computer. Installed recent version `1.1.3`. Then realised i forgot to specify different shared dir. Uninstalled, installed again and i needed to restart my laptop to make hostname work.

**Comment by nlf** [comment]
an ssh config is a good idea, certainly, but it doesn't eliminate the need for an entry in `/etc/hosts`. the user potentially needs to access docker services exposed on the vm, which would be at `local.docker` rather than `localhost`.

the ssh config changes are on my roadmap though, so expect that fairly soon

**Comment by nlf** [comment]
can any of you still experiencing this problem take a look at #135 and see if the next release resolves your issues?

if so, comment there. i'm going to close this issue for now
