### ISSUE TITLE
Provide Makefile for better builds

### ISSUE THREAD

**Issue by leipert** [nlf/dlite#58]
Manually requiring the go dependencies in homebrew is a little bit of a PITA:
https://github.com/leipert/homebrew/blob/add-dlite-formula/Library/Formula/dlite.rb#L13-L76

A Makefile with `make build` target would be awesome. If you want I could help you with that.

Also is there something like a better go dependency management?

**Comment by nlf** [comment]
yeah, i can vendor the dependencies and add a makefile to simplify things for you
