### ISSUE TITLE
Please adopt semver & fixed releases

### ISSUE THREAD

**Issue by erichiggins** [nlf/dlite#6]
It'd be awesome if developers knew which "version" of dlite they had installed on their machines. Since there are no Releases and only a master branch that we're expected to clone, it could lead to inconsistent results for a team of developers. 

Using a tool like [git-flow](https://github.com/nvie/gitflow), along with [semantic versioning](http://semver.org/) should be an easy way to resolve this.

**Comment by nlf** [comment]
yeah this is something i've been meaning to do anyway, the next release will end up being dubbed 1.0.0 and i'll use semantic versioning from there forward

**Comment by nlf** [comment]
as of now, semantic versioning will be respected. in addition, i've added a `dlite version` command to display the currently installed version of dlite

**Comment by erichiggins** [comment]
Awesome. Thanks!
