### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by pdonorio** [nlf/dlite#60]
I installed Dlite three days ago. I like it a lot, but i have also met problems.

The laptop froze twice in the last two days,
both times i opened the lit and the mac resulted down, while i never shut it off.
This problem appeared right after dlite,
i didn't install anything else in the last two weeks.

Do you have any suggestion on what to monitor?
Could it be xhyve or something else?

**Comment by nlf** [comment]
i'm honestly not sure. it's possible it is xhyve related, however. i'd suggest opening an issue there and seeing if anyone has any ideas.

**Comment by pdonorio** [comment]
Thanks for the quick feedback.

I just opened the issue there: mist64/xhyve#86.
you may close this one i guess.
