### ISSUE TITLE
More transparency about used images / docker versions

### ISSUE THREAD

**Issue by leipert** [nlf/dlite#61]
One thing we do at work is pinning down docker versions. We have a private docker registry and it takes more time to upgrade to a new docker version (for example when the docker API changed from 1.7 to 1.8).

That being said, to me it is not too transparent which dlite version uses which [dhyve-os](https://github.com/nlf/dhyve-os) version, which docker versions are being used in dhyve-os. Can I pin them down?

**Comment by nlf** [comment]
dlite downloads the latest version of dhyve-os that's available when the install command is run. the latest version of dhyve-os (with some room for error) will always contain the latest version of docker. you can use the `-v` or `--os-version` flag when running install to grab a specific version of dhyve-os, though be aware that if you do so there are some changes that have not been backported in the os (passing the `--ip` flag to docker and configurable share directories, for example).

if there's enough demand, i could be convinced to build the current OS with older versions of docker embedded, but in the mean time you can also do so yourself. clone the dhyve-os repo, edit the Dockerfile to change the DOCKER_VERSION variable to the version you would like, then run `make`. once it's complete the output directory will contain your kernel and rootfs, you can stop your dlite vm and copy those files to `~/.dlite/` and then start the vm back up to use your custom build

**Comment by leipert** [comment]
Cool. Thanks for your answer. I really like dlite and I would like to push it in our company.

I could also help with automated tests and builds maybe using company resources or free available services travis or wercker.

EDIT: Providing a solid, automated build/test system is a fun thing for me and it would provide a better experience for all of us :+1:

**Comment by nlf** [comment]
i feel like it's reasonable to have builds of dhyve-os for each version of docker, and it would definitely be nice to automate that process.

i'm going to close this issue though, since it's actually relating to the os and not dlite itself. let's start a new issue there to figure out how to make this work.
