### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by nustiueudinastea** [nlf/dlite#62]
Hi Nathan,

First of all, nice project! I am having an issue with dlite, where it borks out with a "exit status 1" message when I do start or stop:

```
~$ sudo dlite install
Building disk image: done
Downloading OS: done
Writing configuration: done
Creating launchd agent: done
~$ dlite start
exit status 1
~$ 
```

Any ideas?

**Comment by nlf** [comment]
check the Console app for errors

**Comment by nustiueudinastea** [comment]
It seems that dlite is performing some actions that require more privileges. 

`28/01/16 22:58:26,272 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.system) Caller not allowed to perform action: launchctl.37053, action = start service, code = 1: Operation not permitted, uid = 501, euid = 501, gid = 20, egid = 20, asid = 100007
`

I don't really understand what permissions it is missing.

**Comment by nlf** [comment]
what version of dlite are you using? also what does the output of `ls -lh ~/Library/LaunchAgents/local.dlite.plist` look like?

**Comment by nustiueudinastea** [comment]
I am using dlite 1.1.1. 

`-rw-r--r--  1 al3x  staff   432B Jan 28 22:53 Library/LaunchAgents/local.dlite.plist`

After a quick google it seems that this issue appears in combination with tmux. Running dlite from a non-tmux shell works. Very weird, will dig deeper to see if it can be fixed in tmux.

**Comment by nlf** [comment]
ah, that makes sense. there's a note about that in the troubleshooting section of the readme :)

i'm going to close this, but please do let me know if you figure out a workaround so i can document it here

**Comment by nustiueudinastea** [comment]
Missed that :| Will take a closer look and get back if I can figure it out.
