### ISSUE TITLE
Build of 1.1.2 fails

### ISSUE THREAD

**Issue by leipert** [nlf/dlite#64]
The vendor path is missing

```
github.com/fatih/color
github.com/mattn/go-colorable
github.com/mattn/go-isatty
```

and if include above manually, then compiling fails:

```
GO15VENDOREXPERIMENT=1 go build
# github.com/nlf/dlite/vendor/github.com/TheNewNormal/libxhyve
vendor/github.com/TheNewNormal/libxhyve/xhyve.go:7:11: fatal error:
      'xhyve/xhyve.h' file not found
 #include <xhyve/xhyve.h>
          ^
1 error generated.
make: *** [dlite] Error 2
```

It seems like the libxhyve package misses a include folder: https://github.com/TheNewNormal/libxhyve/tree/master/include/xhyve

**Comment by leipert** [comment]
fwiw: I get above error with `go get github.com/nlf/dlite` as well.

**Comment by nlf** [comment]
vendoring is hard apparently.. i'll figure it out

**Comment by leipert** [comment]
Yeah. No need to hurry though, as I just load the dependencies manually in the brew Formula. We can replace it with a nice make task in a future release

**Comment by nlf** [comment]
ok.. i just redid the vendoring, can you see if it works for you from the master branch? if it does i'll change the 1.1.2 release to point to the new master

**Comment by leipert** [comment]
Both `go get github.com/nlf/dlite` and an adjusted brew formula work.

I understand why you want to forward the 1.1.2, but that would be bad practice (for example breaking the current, working Formula).

I suggest, that we get the dlite formula merged and once you have a new release with new features, we can migrate to the new build script?

**Comment by nlf** [comment]
works for me, let's leave things as is and the vendoring will get rolled into a new build version later. i'm going to close this. thanks for adding the CI config

**Comment by leipert** [comment]
no problemo :+1:
