### ISSUE TITLE
Network timed out while trying to connect to ...

### ISSUE THREAD

**Issue by haysclark** [nlf/dlite#66]
I am running into an issue with :
- dlite 1.1.2 (via binary)
- Docker 1.9.1
- OSX 10.10.5

```
~ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.
```

I have removed all my boot2docker vm's, the .boot2docker files and the .docker files.  This cleared up some early issues.  Now I have the error above.  One other thing I noticed is this:

```
~dlite ip
192.168.64.6
```

However if I ssh into docker.local and look at _etc/resolv.conf_ it has a different IP, not sure if it matters.  I CAN ping a IP like google.com with no connection issues.  Is there something else I need to cleanup?

```
~ less /etc/resolv.conf
nameserver 8.8.8.8
nameserver 192.168.64.1 # eth0
```

Thanks in advance!

**Comment by nlf** [comment]
does it only time out when pulling images? maybe docker themselves was having network trouble? can you try it again today and see if it's still having trouble?

**Comment by max-winderbaum** [comment]
I'm having the same issue, and am unable to run "wget google.com" from the VM (network is unreachable)... I don't think it's docker hub problem, but rather something that's mis-configured with networking between the VM and host.

@nif I can dump whatever files/config that's relevant. I'll start with ifconfig from both the VM and host:

VM:
https://gist.github.com/max-winderbaum/894ca27b1c2b9a0310b2

Host (OSX 10.11.2):
https://gist.github.com/max-winderbaum/0d01d3dfabea24fcd9a6

**Comment by nlf** [comment]
what does the output of `traceroute docker.io` look like?

**Comment by max-winderbaum** [comment]
https://gist.github.com/max-winderbaum/af8032fee9ba79f2127e 

Looks like it's getting hung up on something... It's weird because I've had this same problem from two different internet providers, and I haven't heard anything from docker.io about being down

**Comment by nlf** [comment]
you're right, that is weird. traffic is clearly making it out of your vm, so it doesn't seem like a routing issue. i'm not sure what else it could be though

**Comment by max-winderbaum** [comment]
@nif thanks so much for your help! I'll keep digging and report my findings back here

**Comment by nlf** [comment]
thank you for your help in investigating. you might check in with the [xhyve](https://github.com/mist64/xhyve) repo to see if anyone has reported something similar

**Comment by max-winderbaum** [comment]
An update: I reinstalled docker-toolbox and everything works fine... I think one of the nodes in the traceroute for docker.io is just not accepting pings, so that cause seems to be a red herring.

I have to get my container working for now so I'll just use docker toolbox, but I'll circle back on this later.

**Comment by jbtule** [comment]
I also have the same issue.

```
OS X 10.11.3 (15D21)
Docker version 1.9.1, build a34a1d5
DLite version 1.1.2
```

I've never had any other docker installations before, I was wanting to try it out.  And it fails just like the original reporter of this issue.

```
~ $ docker run hello-world
Unable to find image 'hello-world:latest' locally
Pulling repository docker.io/library/hello-world
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/hello-world/images. You may want to check your internet connection or if you are behind a proxy.
```

On my local machine I can run this->

```
wget https://index.docker.io/v1/repositories/library/hello-world/images
--2016-01-30 11:57:19--  https://index.docker.io/v1/repositories/library/hello-world/images
Resolving index.docker.io... 54.152.78.181, 54.164.250.255, 52.0.10.162
Connecting to index.docker.io|54.152.78.181|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'images'

images                  [ <=>                  ]   1.53K  --.-KB/s   in 0s     

2016-01-30 11:57:20 (51.4 MB/s) - 'images' saved [1564]
```

If I ssh into the docker vm I get this ->

```
~ $ ssh docker@local.docker
DhyveOS version 2.1.1
Docker version 1.9.1, build a34a1d5
$ wget https://index.docker.io/v1/repositories/library/hello-world/images
Connecting to index.docker.io (52.0.10.162:443)
wget: can't connect to remote host (52.0.10.162): Connection timed out
```

There certainly looks like theres a vm networking issue of some kind.

**Comment by yamilurbina** [comment]
Having this same issue since today:

```
docker run --rm -ti gliderlabs/alpine:3.3 sh
Unable to find image 'gliderlabs/alpine:3.3' locally
Pulling repository docker.io/gliderlabs/alpine
Network timed out while trying to connect to https://index.docker.io/v1/repositories/gliderlabs/alpine/images. You may want to check your internet connection or if you are behind a proxy.
```

```
dlite 1.1.3
docker 1.9.1
```

If I run one of the images I downloaded on the previous days and then I do a traceroute I get this:

```
traceroute docker.io
traceroute to docker.io (54.152.78.181), 30 hops max, 46 byte packets
 1  172.17.0.1 (172.17.0.1)  0.006 ms  0.007 ms  0.002 ms
 2  192.168.64.1 (192.168.64.1)  0.508 ms  0.459 ms  0.260 ms
 3  *  *  *
```

Stuck at 3 and not moving at all. I'll post an update if I find the cause for this.

**Comment by max-winderbaum** [comment]
@nlf is there anything else we can do to help resolve this, now that we've seen this is happening for multiple people?

**Comment by nlf** [comment]
I'm honestly not sure, it sounds like some sort of routing problem but my network engineering days are long past.

I don't recall if anyone got any tips from people in the xhyve repo or not. If not, unless I can figure out how to reproduce it here I'm kind of stuck.

Can you show me the output of `sudo iptables -v -L` and `sudo iptables -t nat -v -L`? maybe it's as simple as an errant firewall rule..

**Comment by nlf** [comment]
this issue has gone stale for nearly a month. i'm going to close this issue and encourage anyone having this problem to see #135 for details on testing the next release

**Comment by jbijoux** [comment]
I had the problem, tried nameserver 8.8.8.8 i restarted VirtualBox, it was then ok, my guess, network changed and VirtualBox DHCP went off sync
