### ISSUE TITLE
Insecure Registry Usage

### ISSUE THREAD

**Issue by pfortin-urbn** [nlf/dlite#67]
As an enterprise user I would like a method to pass an insecure registry to the VM so that we can use the enterprise docker hub images from our Macs.

docker-machine has the --insecure-registry option.

I did get this to work by changing the /etc/init/d/S51docker script to include the IP address of the registry but I could not get to use out DNS name as it said bad address.  It seems we need a way as well to send it new nameservers and host file entries.

**Comment by nlf** [comment]
the easier file to edit is probably `/etc/default/docker` but i'll look into add a flag to the cli for this also. i'm thinking a `--docker-args` so that it can encompass anything the user wants to pass rather than me having to mirror all of the daemon's options

**Comment by pfortin-urbn** [comment]
I tried to edit the /etc/default/docker but nothing happened.  Also we need to be able to add an enterprise DNS server in the docker build machine.

**Comment by nlf** [comment]
even after restarting the service nothing happened?

**Comment by pfortin-urbn** [comment]
Correct

**Comment by nlf** [comment]
weird. ok i'll see what i can do. this is a good idea to add a flag for it anyway

**Comment by nlf** [comment]
closing in favor of #90
