### ISSUE TITLE
dlite Process Consumes 99% of CPU

### ISSUE THREAD

**Issue by silvamerica** [nlf/dlite#68]
I was not using anything related to Docker when I noticed the fans on my computer start to spin. I checked Activity Monitor and dlite was using 99% CPU (it was allocated 1 CPU).

I was easily able to resolve it by running `dlite stop`, however I'm not sure how to go about debugging this when it happens again.

**Comment by nlf** [comment]
if it happens again, ssh in to the dlite vm via `ssh docker@local.docker` and run `top` that should show you what process inside the vm is using so much cpu. let me know what you find out. the only time i've seen this happen myself is when i have a docker container go crazy, so if you have something else going on it would be good to track it down and fix it

**Comment by silvamerica** [comment]
Will do!

**Comment by silvamerica** [comment]
Inside dlite vm:

```
Mem: 1508400K used, 543440K free, 120340K shrd, 60K buff, 331016K cached
CPU:  75% usr  20% sys   0% nic   3% idle   0% io   0% irq   0% sirq
Load average: 3.61 1.83 0.97 4/236 821
```

CPU load fluctuates up and down. Outside dlite it's preetty consistently 96%-100%.

**Comment by nlf** [comment]
the list of processes below that status information should show something with a large number under the CPU column, does it?

**Comment by silvamerica** [comment]
Nope. There are a few things using 25%, but nothing big.

**Comment by nlf** [comment]
25% isn't exactly idle, how many things are running that high and what are they?

**Comment by silvamerica** [comment]
There are a couple Ruby unicorn workers, but they're not staying at 25%. They're spiking that high. There are snapshots from top with all processes reporting 0% except one reporting 2% (ksoftirqd), while to MacOS dlite is consuming 100%.

**Comment by nlf** [comment]
if you stop the docker service inside the vm (`sudo /etc/init.d/S51docker stop`) does the cpu usage go down?

**Comment by silvamerica** [comment]
```
Stopping docker: umount: can't unmount /sys/fs/cgroup/memory: Device or resource busy
umount: can't unmount /sys/fs/cgroup: Device or resource busy
OK
```

Then CPU usage drops.

**Comment by nlf** [comment]
sounds like your docker containers are using just enough cpu to keep things spinning. it is kind of strange that the cpu usage numbers don't seem to match up though. can you start docker back up and show me the output of `docker info`?

**Comment by silvamerica** [comment]
I think I've figured it out.  I had a process that was starting and stopping, so top inside the VM wasn't always catching it using up CPU, while Mac Activity Monitor was!

**Comment by nlf** [comment]
good catch! that makes sense. thanks for letting me know
