### ISSUE TITLE
Can't lock files on NFS mounted volume

### ISSUE THREAD

**Issue by cwndrws** [nlf/dlite#69]
Seems that you can't get a lock in a volume mount. Here is some code that reproduces:

``` python
import os
import fcntl
full_path = "/tmptmp/locktest.txt"
f = os.open(full_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, 'O_BINARY', 0))
def fd(f):
    return hasattr(f, 'fileno') and fileno() or f
try:
    fcntl.lockf(fd(f), fcntl.LOCK_EX)
finally:
    fcntl.lockf(fd(f), fcntl.LOCK_UN)
    os.close(f)
    os.remove(full_path)
```

run that inside of a docker container with '/tmptmp' as a volume mount to reproduce. [This](http://serverfault.com/questions/61594/what-does-no-locks-available-mean) leads me to believe there is no lock daemon running to handle this.

The stack trace here:

```
Traceback (most recent call last):
  File "/tmptmp/nfs_lock_test.py", line 8, in <module>
    fcntl.lockf(fd(f), fcntl.LOCK_EX)
IOError: [Errno 37] No locks available
```

**Comment by cwndrws** [comment]
Can reproduce outside of python:

``` bash
docker run --rm -ti -v "$(pwd):/mnt" ubuntu /bin/bash -c "exec 3>/mnt/lock.txt && flock -x 3"
```

**Comment by nlf** [comment]
you're right, there's no lock daemon currently. i'll work on it

**Comment by nlf** [comment]
added the lock daemon to dhyve-os 2.1.1, which i just published. also confirmed this fixed your issue
