### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by emmanuel** [nlf/dlite#7]
I was a big fan of dhyve, and I must say that you've outdone yourself with dlite. 

Bravo!

**Comment by nlf** [comment]
thanks :) glad you like it. i'm working on rewriting it in go, which will make it so it doesn't require homebrew or any external dependencies. keep an eye out, i should be finished with it inside the next few weeks!

**Comment by emmanuel** [comment]
Also, FWIW, I'm in Seattle, and I'd be delighted to buy you a beverage and say 'hi' if you find yourself around this way some time.

**Comment by nlf** [comment]
that's a really nice offer! i'll keep that in mind next time i'm up there. if you're ever in the tri-cities area, you should drop me a line as well

**Comment by emmanuel** [comment]
One last thing: at work, I need my Docker daemon configured to go through an HTTP proxy. Elsewhere, I need it to not try to go through a proxy. 

I am currently SSHing in to the VM, (un)commenting a line in `/etc/defaults/docker`, and restarting dlite per the instructions in the README. Do you have any quick thoughts about smart(er) ways to accomplish that?

**Comment by nlf** [comment]
hmm.. you could put a bash script `switch` in the docker user's home directory that makes the change (or just switches between two copies of /etc/defaults/docker) and restarts the docker daemon, then you can `ssh docker@local.docker ./switch`

i can look into making that a little simpler to do in the next revision also

**Comment by nlf** [comment]
note that you can restart just the docker daemon by running `sudo /etc/init.d/S51docker restart`

**Comment by emmanuel** [comment]
Thanks! Both of those are great suggestions. I was thinking that simply restarting the daemon should be pretty quick (faster than restarting the VM, at least). Thanks for the tip about how to restart it!
