### ISSUE TITLE
Add some xhyve hardware requirements

### ISSUE THREAD

**Issue by haysclark** [nlf/dlite#71]
I ran into this issue this evening trying to get _dlite_ running on my older Mac Pro and my MacBook Air.  It looks like _xhyve_ requires hypervisor support and some older hardware does not support this even if you are running OSX 10.10.5: http://apple.stackexchange.com/questions/220323/what-are-the-hardware-requirements-for-hypervisor-framework

So you can save yourself some time and run this command and verify that you can run _hypervisor_ and thus _dlite_.

`sysctl kern.hv_support`

kern.hv_support: 0 == sadness
kern.hv_support: 1 == joy

I am in double sadness land because my late-2010 MacBook Air and my 2009 MacPro do not support _hypervisor_.  :(  Maybe the README.md file could be updated to reflect this requirement.

**Comment by nlf** [comment]
good find, i'll add that note to the readme
