### ISSUE TITLE
Expose docker API port

### ISSUE THREAD

**Issue by franklinkim** [nlf/dlite#72]
In order to work with i.e. wercker you need to expose the docker api port `2375`.

Current workaround would be to use port portwording like:

``` bash
$ ssh -L 2375:192.168.64.2:2375 -N docker@local.docker
```

**Comment by nlf** [comment]
wait.. it requires the port exposed at 2375 on the host machine? you can't point it at a different host?

**Comment by nlf** [comment]
port 2375 is exposed from the virtual machine, and i really find it hard to believe that wercker is incapable of pointing at a different host. i'm going to close this unless there's a strong argument as to why it's needed

**Comment by franklinkim** [comment]
Wercker has an option to define the host ie.

```
$ wercker dev --docker-host tcp://192.168.64.2:2375
```

but it just can't connect to it. But maybe that's only on my machine for some reaseon, so let's see if this comes up again. Thanks anyway!! Really great tool!!!
