### ISSUE TITLE
Creating launchd agent: ERROR!

### ISSUE THREAD

**Issue by tnguyen14** [nlf/dlite#74]
Trying this out for the first time today. Following the instruction to install dlite, and got the following error:

```
:; sudo dlite install
Password:
Building disk image: done
Downloading OS: done
Writing configuration: done
Creating launchd agent: ERROR!
open /Users/tri/Library/LaunchAgents/local.dlite.plist: no such file or directory
```

**Comment by kitten** [comment]
Maybe the Launch Agent folder is missing? 

`mkdir -p /Users/tri/Library/LaunchAgents`

**Comment by tnguyen14** [comment]
Yup, that was it. Thanks @philpl. Wondering if that's worth documenting?

**Comment by nlf** [comment]
I'll tweak the code to make sure that directory exists. Good find
