### ISSUE TITLE
launchctl start local.dlite ends with status 1

### ISSUE THREAD

**Issue by mkatrenik** [nlf/dlite#75]
`launchctl start local.dlite` ends with status 1. Deleting `/etc/exports` doesn't help. But `sudo dlite daemon` works.

dlite version: 1.1.2

**Comment by nlf** [comment]
Can you check the Console app for errors when you try to start the service?

**Comment by robhurring** [comment]
Getting same issue here, console.log has:

```
$ sudo dlite start
$ exit status 3

com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): Caller specified a plist with bad ownership/permissions: path = /Users/USER/Library/LaunchAgents/local.dlite.plist, caller = launchctl.38348
```

```
$ dlite start
$ exit status 1

com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.system): Caller not allowed to perform action: launchctl.40256, action = start service, code = 1: Operation not permitted, uid = 502, euid = 502, gid = 20, egid = 20, asid = 100007
```

And the plist is:

``` plist
<plist version="1.0">
  <dict>
      <key>Label</key>
        <string>local.dlite</string>
        <key>ProgramArguments</key>
        <array>
          <string>/usr/bin/sudo</string>
          <string>/Users/USER/bin/dlite</string>
            <string>daemon</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
  </dict>
</plist>
```

EDIT: `sudo dlite daemon` also works, version 1.1.3

**Comment by nlf** [comment]
what does the output of `ls -l ~/Library/LaunchAgents/local.dlite.plist` look like?

**Comment by mkatrenik** [comment]
in my case:
`-rw-r--r--  1 katrenik  1772764646  442 Feb  1 16:36 /Users/katrenik/Library/LaunchAgents/local.dlite.plist`

**Comment by mkatrenik** [comment]
One thing - it stopped working after system restart

**Comment by nlf** [comment]
your permissions got messed up somehow, try running `chown katrenik:staff ~/Library/LaunchAgents/local.dlite.plist` and then try starting it again

**Comment by mkatrenik** [comment]
no luck `com.apple.xpc.launchd[1] (local.dlite[12400]): Service exited with abnormal code: 1`

**Comment by nlf** [comment]
nothing else in the log around that?

**Comment by mkatrenik** [comment]
no

**Comment by nlf** [comment]
but it works correctly if you just run `sudo dlite daemon`?

**Comment by mkatrenik** [comment]
yes

**Comment by nlf** [comment]
can you run `sudo visudo` and verify that the line added to sudoers at the very bottom has the correct path to the `dlite` binary?

**Comment by mkatrenik** [comment]
yea, it's correct

**Comment by nlf** [comment]
and the contents of the plist? i see you pasted `<string>/Users/USER/bin/dlite</string>` as the path, but was that you replacing your username with USER or is that how the plist actually is?

**Comment by mkatrenik** [comment]
I've upgraded to 1.1.3 and can't run `sudo dlite daemon` anymore - `virtio_net: Could not create vmnet interface, permission denied or no entitlement?`

**Comment by nlf** [comment]
run `sudo dlite uninstall` and `sudo dlite install` again and see if that fixes it, i'm guessing i may have accidentally broke something in the config changes :/

**Comment by mkatrenik** [comment]
works :-)

**Comment by nlf** [comment]
great! sounds like maybe something in the older version of dlite you were using was causing a problem.. i'm gonna go ahead and close this, but if it happens to you again please do reopen the issue and let me know

**Comment by mkatrenik** [comment]
sorry, i mean `sudo dlite daemon` works, but not `dlite start` :-(

**Comment by nlf** [comment]
oh! my fault for assuming

**Comment by mkatrenik** [comment]
hmm, i'm trying to debug launchctl & play with dtrace, but everything seems broken in yosemite, mostly because of that change to permissions system :-(

**Comment by nlf** [comment]
the permissions on the plist? or what?

**Comment by mkatrenik** [comment]
i mean some dtrace scripts like iosnoop are broken, or launchctl lost log command and so on ...

**Comment by nlf** [comment]
oh, i see. because of the yosemite rootless nonsense. yeah, it makes things a bit more awkward to figure out :/

**Comment by mkatrenik** [comment]
i don't understand this stuff much but seems like issue with permissions

```
sudo execsnoop -v

STRTIME                UID    PID   PPID ARGS
dtrace: error on enabled probe ID 2 (ID 269: syscall::execve:return): invalid kernel access in action #8 at DIF offset 0



sudo opensnoop -ve

dtrace: error on enabled probe ID 5 (ID 161: syscall::open:return): invalid user access in action #9 at DIF offset 0
dtrace: error on enabled probe ID 6 (ID 947: syscall::open_nocancel:return): invalid user access in action #9 at DIF offset 0
dtrace: error on enabled probe ID 5 (ID 161: syscall::open:return): invalid user access in action #9 at DIF offset 0



sudo errinfo -c

EXEC          SYSCALL  ERR  COUNT  DESC
dlite           select    4      1  Interrupted system call 
dlite            csops   22      2  Invalid argument 
dlite        sigreturn   -2      2 
dlite            wait4   -1      2 
dlite    psynch_cvwait  316   1210 
```

**Comment by nlf** [comment]
interesting. if you run `sudo -k && sudo dlite daemon` are you prompted for a password?

**Comment by mkatrenik** [comment]
no

**Comment by nlf** [comment]
i'm running out of ideas.. this is a weird one

**Comment by nlf** [comment]
`/Users/USER/bin` is in your path, right? so if you run `which dlite` that's the path that shows up?

**Comment by mkatrenik** [comment]
yes, but i have created this directory by me some time ago, if that's important

**Comment by nlf** [comment]
nah that shouldn't matter, just wanted to confirm the same binary was being run by both your shell and the plist

**Comment by mkatrenik** [comment]
it works! until now i was creating it with different ssh key than id_rsa & when i tried to log in - it wanted password, so recreated it again & it works.

**Comment by nlf** [comment]
even while using the plist?

**Comment by mkatrenik** [comment]
that doesn't work, only `dlite start`

**Comment by nlf** [comment]
oh. well then. i'm going to close this, but i opened another issue to track figuring out what's going on with alternate ssh keys

**Comment by gerhard** [comment]
I am having exactly the same issue after upgrading from 1.1.4 to 1.1.5:

`dlite start` exits 0, logs:

```
19/04/2016 07:31:57.793 com.apple.xpc.launchd[1]: (local.dlite[60739]) Service exited with abnormal code: 1
```

`sudo dlite start` exits 1, logs:

```
19/04/2016 07:33:59.603 com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.domain.system) Caller specified a plist with bad ownership/permissions: path = /Users/gerhard/Library/LaunchAgents/local.dlite.plist, caller = launchctl.60749
```

`dlite daemon` exits 1 with `This command requires sudo`

`sudo dlite daemon` works:

```
COM1 connected to /dev/ttys001
rdmsr to register 0x570 on vcpu 0
rdmsr to register 0x34 on vcpu 0
```

Launchctl file permissions are correct:

```
-rw-r--r--  1 gerhard  staff  450 19 Apr 07:26 /Users/gerhard/Library/LaunchAgents/local.dlite.plist
```

Sudo permissions are correct:

```
gerhard ALL=(ALL) NOPASSWD: /sbin/nfsd,/usr/local/Cellar/dlite/1.1.5/bin/dlite
```

Checking now if a restart fixes it... Yes, restart fixes it. The good old stop & start 👴
