### ISSUE TITLE
support sparse disk image

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#76]
need to implement something to enable sparse disk support, probably the raw disk patch that has already been merged into libxhyve

**Comment by jrk** [comment]
I came to see if anyone had asked about the surprisingly large base image size. It seems like this is likely the culprit—it's preallocating 30gb by default, even if the raw OS install uses very little of that?

**Comment by ruimarinho** [comment]
It was recently added to the README (https://github.com/nlf/dlite/commit/55429f36fc418c8abca2891d24db269c8b3589b3) so I guess we have to wait for that feature to become available to dlite :) but indeed, it will be a very welcome one (even if those 30Gb are going to fly in a very short amount of time..)
