### ISSUE TITLE
dlite start exits 1

### ISSUE THREAD

**Issue by ch3pjw** [nlf/dlite#78]
`dlite version` => `1.1.3`

I followed the installation instructions from your `README`, creating the missing `Library/LaunchAgents` directory it complained about (which I think is fixed on master). Everything purportedly worked fine.

However, `dlite start` just gives me `exit status 1`. I've logged out and back in again, but not rebooted my machine. The `rebuild` and `update` commands work fine. The `ip` command times out, and I can't resolve the default `local.docker` hostname.

Am I missing some pre-requisite that isn't mentioned in the docs? Is there any way to get some more diagnostic information that `exit status 1`?

**Comment by robhurring** [comment]
I am having the same issue, yesterday this was tracked in https://github.com/nlf/dlite/issues/75 -- I haven't tried the suggestions in that thread yet, but it may help.

**Comment by ch3pjw** [comment]
@robhurring: thanks - I've had a read through. The permissions of `~/Library/LaunchAgent` were indeed wrong, but rectifying them didn't appear to fix my issue, even after a reinstall. I tried `sudo dlite daemon` just for a laugh, and that actually appears to work (though I hadn't tried it before).

**Comment by ch3pjw** [comment]
Hmm, I tried updating the VM image again, and `sudo dlite daemon` now gives me `virtio_net: Could not create vmnet interface, permission denied or no entitlement?` and I still get `dlite start` giving `exit status 1`

**Comment by nustiueudinastea** [comment]
@ch3pjw are you using tmux?

**Comment by ch3pjw** [comment]
Yes!

**Comment by nustiueudinastea** [comment]
That's the problem. It's even mentioned in the dlite readme that tmux causes issues(I missed it myself as well). If you run dlite commands outside of tmux everything should work as expected.

**Comment by ch3pjw** [comment]
Yeah, just been trying that right now - commands exit fine now. I'm not sure that the daemon is actually up-and-running properly yet (`dlite install`, `dlite start` appear to work fine, but then a subsequent `docker version` still only gives me the client version and says it can't connect to the daemon :-(

However, as far as my original issue goes, this is now fixed. Thanks!

**Comment by ch3pjw** [comment]
Patience was all that was required, as the dlite VM took a while to boot :-)
