### ISSUE TITLE
what's the default password for fresh install?

### ISSUE THREAD

**Issue by rcholic** [nlf/dlite#80]
I just installed dlite on my mac, however, I was prompted to enter password when I try to access `ssh local.docker`. I don't think I ever set the password during the install. Any ideas? thanks

**Comment by nlf** [comment]
`ssh docker@local.docker` should use your ssh key and not prompt for a password, if it does try `ssh root@local.docker` with the password `dhyve`

**Comment by rcholic** [comment]
thanks, that works!

On Tue, Feb 2, 2016 at 12:02 PM, Nathan LaFreniere <notifications@github.com

> wrote:
> 
> ssh docker@local.docker should use your ssh key and not prompt for a
> password, if it does try ssh root@local.docker with the password dhyve
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nlf/dlite/issues/80#issuecomment-178688962.

## 

☃ (__/)
          (='.'=)
          (")_(")
- 温 良 恭 俭 让 仁 义 礼 智 信
- Through suffering to renown

**Comment by adis-io** [comment]
@nlf 
Sorry, but I just installed and it asks for password too. `dhyve` doesn't work.

**Comment by nlf** [comment]
yeah i've actually recently seen it fail myself. i'll reopen this while i investigate

**Comment by herrbischoff** [comment]
Any news regarding this? I'm stuck with not being able to login as well.

**Comment by nlf** [comment]
root/dlite is now the default credentials which i have yet to see fail
