### ISSUE TITLE
Boot2docker CA Certificate error

### ISSUE THREAD

**Issue by kidush** [nlf/dlite#82]
When I try to run `docker run hello-world` the error below appears to me:

Could not read CA certificate "/../.boot2docker/certs/boot2docker-vm/ca.pem": open /../.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory

I'm already removed boot2docker files, but it always happens.

**Comment by nlf** [comment]
```
unset DOCKER_CERT_PATH
unset DOCKER_TLS_VERIFY
```

sounds like maybe something is setting those variables for you, but if you unset them it should work correctly

**Comment by kidush** [comment]
woow o/ thanks @nlf
