### ISSUE TITLE
Allow change of memory setting without VM reinstall

### ISSUE THREAD

**Issue by 14to9** [nlf/dlite#83]
Just raised my memory setting (to 4G) and had to `dlite uninstall` and `dlite install -m 4` to get this to work. 

Side effect was of course that my VM disk was lost.   Could we get maybe a 

```
dlite update -m 4
```

or similar to allow the VM to be reconfigured without a total rebuild of the VM?

**Comment by ruimarinho** [comment]
I was able to edit the json config file and simply restart the machine to get the new memory setting available.

**Comment by nlf** [comment]
right, it could definitely be made more clear, but editing the `~/.dlite/config.json` file and then a quick `dlite stop && dlite start` would work

**Comment by caseywebdev** [comment]
Good to know about the `config.json`. `dlite stop` and `dlite start` don't seem to be valid commands though? I've been restarting `dlite` through `launchctl`.

**Comment by caseywebdev** [comment]
My mistake, I wasn't using the latest version of dlite.

**Comment by nlf** [comment]
i'm gonna close this issue and open a new one to add a command for reconfiguring the vm
