### ISSUE TITLE
Add support for setting dns server

### ISSUE THREAD

**Issue by ruimarinho** [nlf/dlite#86]
I'd like to set a fixed IP address and netmask (CIDR) for the `docker0` bridge (`--bip`), as well as a custom dns server (`--dns`).

Currently, this can be achieved by manually editing `/etc/default/docker` and adding the extra arguments. Would it be possible to make this configurable when creating the machine, akin to the memory and cpu settings?

**Comment by nlf** [comment]
not yet, but it's a good idea

**Comment by nlf** [comment]
closing in favor of #90
