### ISSUE TITLE
add configuration command

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#89]
considering a command that would, ideally
- stop the daemon
- open the config file in $EDITOR
- start the daemon after the user quits the editor

i'm not 100% sold if this is needed, or if we should just document how to edit the file and restart dlite and be happy

**Comment by leipert** [comment]
I would love that, especially if the init script which installs docker is added (see https://github.com/nlf/dhyve-os/issues/14)

edit and see : https://github.com/nlf/dhyve-os/issues/16

**Comment by mageekguy** [comment]
The README says `Next, edit your config file for DLite via dlite config. Set the value of the "extra" option to "--bip=172.17.0.1/24 --dns=172.17.0.1" and exit your editor.`.
However, the master branch does not contain `dlite config`.

**Comment by nlf** [comment]
yes it does.. it only exists in the master branch (which corresponds to the latest 2.0.0-beta pre-release). if you installed via homebrew you won't have it because 2.0.0 isn't finished yet, and as such isn't in homebrew
