### ISSUE TITLE
add flag and config item for passing extra arguments to docker

### ISSUE THREAD

**Issue by nlf** [nlf/dlite#90]
see #86 and #67

**Comment by p4tin** [comment]
I'd like to help with a PR but if you could give me some direction it might speed me up a bit...

**Comment by pfortin-urbn** [comment]
I'd like to help with a PR but if you could give me some direction it might speed me up a bit...

**Comment by bentruyman** [comment]
Having this ability could increase our use of `dlite`. On VPN `dlite` is unusable as it can't reach our internally resolved servers whereas a `boot2docker` instance using the host machine's DNS resolving abilities can.

If it helps, in the past I've provisioned a VirtualBox VM using the following:

```
VBoxManage modifyvm “boot2docker-vm" --natdnshostresolver1 on
```

**Comment by pfortin-urbn** [comment]
@bentruyman - I have gotten around this temporarily by creating my own dhyve-os (https://github.com/nlf/dhyve-os) if you change the /etc/resolve.conf to hold your dns servers it will work.  As well, we have an insecure docker image server which I just added to the /etc/defaults/docker file and now I can use dlite within our enterprise environment.
