### ISSUE TITLE
Use fingerprint to validate OS artifacts

### ISSUE THREAD

**Issue by benschumacher** [nlf/dlite#92]
I've been trying to use dlite for a couple of days, and it hasn't been working for me. I finally figured out that for some reason (my guess: misbehaving proxy) the download of the OS artifacts was failing, and therefore the OS was never booting. I got a variety of errors.

My suggestion: use some sort of checksum to ensure that the artifacts are downloaded successfully.

**Comment by nlf** [comment]
that's an interesting problem.. i'll see if i can figure something out

**Comment by nlf** [comment]
this is closed via #112
