### ISSUE TITLE
dlite install does things as root: interactively explain what

### ISSUE THREAD

**Issue by lloeki** [nlf/dlite#94]
`sudo dlite install` does things. I could not find a place where it told what it's doing.

OK `dlite uninstall` undoes whatever it does, but `dlite install` should probably tell what it's going to do beforehand and ask `[y/N]` for permission to do it (unless invoked with a possible `dlite install -y`). As it is it silently does stuff to system files.

As an example, see how installing Homebrew warns about the `sudo` stuff it will perform.

**Comment by nlf** [comment]
yeah i'll add a warning when the install command is run that informs the user what's about to happen. that's a good idea, thanks for the suggestion!
