### ISSUE TITLE
Stdin is not forwarded to VM

### ISSUE THREAD

**Issue by djui** [nlf/dlite#96]
Running `echo hi | docker run -i debian cat` results in no output.

Running from within the VM works.

```
$ ssh docker@docker.local
DhyveOS version 2.2.0
Docker version 1.10.0, build 590d5108
$ echo hi | docker run -i debian cat
hi
```

The following seems to indicate that `stdin` (0) is a valid pipe:

```
$ docker run -i debian /bin/ls -l /proc/1/fd
total 0
lr-x------ 1 root root 64 Feb  9 15:46 0 -> pipe:[14817]
l-wx------ 1 root root 64 Feb  9 15:46 1 -> pipe:[14821]
l-wx------ 1 root root 64 Feb  9 15:46 2 -> pipe:[14822]
lr-x------ 1 root root 64 Feb  9 15:46 3 -> /proc/1/fd
```

While this does not (which I don't see related to this problem):

```
$ docker run -a stdin -a stdout -a stderr debian /bin/ls -l /proc/1/fd
total 0
lrwx------ 1 root root 64 Feb  9 15:39 0 -> /dev/null
l-wx------ 1 root root 64 Feb  9 15:39 1 -> pipe:[12342]
l-wx------ 1 root root 64 Feb  9 15:39 2 -> pipe:[12343]
lr-x------ 1 root root 64 Feb  9 15:39 3 -> /proc/1/fd
```

This also already didn't work with Docker 1.9.

```
$ docker info
Containers: 36
 Running: 0
 Paused: 0
 Stopped: 36
Images: 245
Server Version: 1.10.0
Storage Driver: btrfs
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host bridge
Kernel Version: 4.3.3-dhyve
Operating System: Buildroot 2015.11.1
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.957 GiB
Name: dlite
ID: 2ZYZ:W7FP:7WNQ:Z6GB:RQV3:MXS5:IMPI:ERMG:Q4QS:P4RY:M4I4:NEQY
Username: djui
Registry: https://index.docker.io/v1/
```

```
$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64
```

```
$ uname -a
Darwin Daftpunk.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin
```

**Comment by rdrey** [comment]
I can reproduce this. I'm not sure if this is a different issue or related, but even the basic tutorial `docker run ubuntu /bin/echo 'Hello world'` only produces stdout for me when running inside the dlite VM. It does print Hello World when I run it in interactive mode outside the VM, though (`docker run -i ubuntu /bin/echo 'Hello world'`), which is very weird since I don't see why it would need stdin to work.

**Comment by djui** [comment]
Also interesting example you gave.

Maybe it helps to use the XHyve Driver for docker-machine someone wrote and see how this behaves.

**Comment by djui** [comment]
I think we are not there yet, but it's getting better: The example mentioned above `echo hi | docker run -i debian cat` now correctly prints `hi` but hangs and never returns. Neither SIGINT, SIGHUP, nor SIGQUIT terminates the process and returns to the shell. I have to `dlite stop && dlite start` to use docker again.

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
3a7bfeb73bab        debian              "cat"               5 minutes ago       Up 5 minutes                            gigantic_swirls

$ docker logs 3a7bfeb73bab
hi

$ kill -TERM 45174
$ kill -HUP 45174
$ kill -INT 45174
$ kill -ABRT 45174
$ kill -QUIT 45174
$ kill -KILL 45174
[1]    45173 done       echo hi |
       45174 killed     docker run -i debian cat
```

Running the same example from within DhyveOS works (i.e. the command returns to shell).

**Comment by nlf** [comment]
hmm, that's interesting. it must be keeping the connection open for some reason. i'll see what i can find.

**Comment by djui** [comment]
From what I can tell https://github.com/nlf/dlite/blob/master/utils/proxy.go#L77 does not return. Instrumenting the write part shows:

``` go
:
written, err := io.Copy(backend, conn)
log.Println(">>>", written, err)
:
```

```
2016/02/18 22:40:07 >>> 3 <nil>
```

``` go
:
written, err := io.Copy(conn, backend)
log.Println("<<<", written, err)
:
```

```
[never printed]
```

**Comment by nlf** [comment]
that's interesting.. that would imply that the backend is never sending any response

**Comment by djui** [comment]
Looks like backend is sending a response, but with no body / not EOF terminating it:

``` go
 //io.Copy(conn, backend)
log.Println("<<< Before")
tee := io.TeeReader(backend, os.Stderr)
written, err := io.Copy(conn, tee)
log.Println("<<< After", written, err)
```

```
2016/02/18 23:14:05 <<< Before
HTTP/1.1 101 UPGRADED
Content-Type: application/vnd.docker.raw-stream
Connection: Upgrade
Upgrade: tcp

2016/02/18 23:14:05 >>> 3 <nil>
hi
```

**Comment by nlf** [comment]
well that makes things tricky, how can we know when to close the connection if we never get an EOF..
