### ISSUE TITLE
Install SSH problems

### ISSUE THREAD

**Issue by nwillems** [nlf/dlite#97]
During installation of the xhyve host, it reports an error.

```
$ sudo dlite install
Password:
Building disk image: ERROR!
open /Users/nwillems/.ssh/id_rsa.pub: no such file or directory
```

This is probably due to not having a RSA SSH-key. I would suggest dlite to maintain it's own set of SSH keys and then ask the user to add to the ssh-config.

Key-generation `$ ssh-keygen -t RSA -b 4096 -f ~/.dlite/id_rsa -N ''`, and config template:

```
Host local.docker
    IdentityFile ~/.dlite/id_rsa
    User docker
```

/Nicolai

**Comment by cmosetick** [comment]
@nwillems Thank you for your report! Please see the existing issues and comments on #48 and #77 before creating a new issue with the same problem. Thanks!

**Comment by nwillems** [comment]
Thank you. I will port my comments/ideas to the other issues and close this one.

And to be clear - this is an amazing piece of software, thank you for putting the effort into it. Hopefully I will have the time to resolve this.
