### ISSUE TITLE
[Support][Bug] Output not redirected

### ISSUE THREAD

**Issue by nwillems** [nlf/dlite#98]
After successfully installing dlite and have docker running, just to verify, I ran through the "Getting started" from docker. 

Running the `hello-world` image(`$ docker run hello-world`) went "fine", except the output didn't show. Just to verify, I SSH to the virtual machine and ran the same docker command - all good. To verify even more, I deleted the containers and the image, and re-ran, still working when SSH to the machine.

I'm not completely sure why, if any further info needed please ask.
Version info:

```
Client Docker: 1.10.0
Server Docker: 1.10.0
dlite 1.1.3
OSX: 10.11.3
```

/Nicolai

**Comment by cmosetick** [comment]
@nwillems I am able to reproduce your results. However, simply running the command interactively from the OS X system yields the expected output.

i.e.
`docker run -i hello-world`

I'm not sure if that helps you out or makes you feel better, but it is a valid workaround for now.

**Comment by nwillems** [comment]
Thank you for the feedback, seems like a good workaround.

**Comment by nwillems** [comment]
:+1: Amazing. Thank you.

**Comment by nlf** [comment]
glad it worked for you, thanks for reporting the problem in the first place!
