### ISSUE TITLE
Docker run -u option does not work

### ISSUE THREAD

**Issue by chris-codaio** [nlf/dlite#99]
It looks like the docker run -u option is not working properly - this seems to be the my last hurdle before I can switch our dev team over to dlite for a true container-based hermetic build environment!

I'm guessing we need to get the local user/group information into the dhyve-os VM?

**Comment by nlf** [comment]
hmm.. yeah, we would need to somehow replicate the users and groups from the host into the vm. this should be possible, but won't be easy for sure

**Comment by nlf** [comment]
just to confirm - the users you would be interested in replicating are all created by you? no built in OS X users?

**Comment by chris-codaio** [comment]
That's correct.  And I'd venture a guess that most Mac machines which host
docker have a single interactive dev user... Just getting that single
user/group working would probably solve a majority of the dev/test
scenarios.

**Comment by nlf** [comment]
that was my assumption too, just wanted to make sure that you (as the only person that's asked for it) didn't have the need for more than that

**Comment by chris-codaio** [comment]
Nice!!  I'm looking forward to picking up this change as soon as homebrew has the latest goodness. :)
